-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 28 Ian 2015 la 18:18
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `news`
--

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `locale`
--

CREATE TABLE IF NOT EXISTS `locale` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `us` varchar(255) CHARACTER SET utf8 NOT NULL,
  `ro` varchar(255) CHARACTER SET utf8 NOT NULL,
  `fr` varchar(255) CHARACTER SET utf8 NOT NULL,
  `nl` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=16 ;

--
-- Salvarea datelor din tabel `locale`
--

INSERT INTO `locale` (`id`, `us`, `ro`, `fr`, `nl`) VALUES
(1, 'Home', 'Acasă', 'Accueil', 'Home'),
(2, 'Country', 'Ţara', 'Pays', 'Platteland'),
(3, 'About', 'Despre', 'Contact', 'aboutnl'),
(4, 'Read more', 'Citeşte mai mult', 'En savoir plus', 'rmnl'),
(9, 'Filters', 'Filtre', '', NULL),
(10, 'Choose a date', 'Alege o dată', '', NULL),
(11, 'Today', 'Azi', '', NULL),
(12, 'Yesterday', 'Ieri', '', NULL),
(13, 'All', 'Toate', '', NULL),
(14, 'Choose a media', 'Alege un autor', '', NULL),
(15, 'There are no news under this settings. Please refine your filters.', 'Nu sunt ştiri cu aceste setări. Vă rugăm alegeţi alte filtre.', '', NULL);

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `news`
--

CREATE TABLE IF NOT EXISTS `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_id` int(11) NOT NULL,
  `author` varchar(255) CHARACTER SET utf8 NOT NULL,
  `title` varchar(255) CHARACTER SET utf8 NOT NULL,
  `description` varchar(1000) CHARACTER SET utf8 NOT NULL,
  `site_link` varchar(255) CHARACTER SET utf8 NOT NULL,
  `link` varchar(255) CHARACTER SET utf8 NOT NULL,
  `pubdate` varchar(255) CHARACTER SET utf8 NOT NULL,
  `views` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=130 ;

--
-- Salvarea datelor din tabel `news`
--

INSERT INTO `news` (`id`, `country_id`, `author`, `title`, `description`, `site_link`, `link`, `pubdate`, `views`) VALUES
(1, 3, 'cnn.com', 'Residents warned to stay inside during blizzard', 'Up to 58 million people could be affected by a "crippling" winter storm, with blizzard warnings in place along the U.S.''s northeastern coast from New Jersey to Maine.', '/us/residents-warned-to-stay-inside-during-blizzard', 'http://edition.cnn.com/2015/01/27/us/weather-storm/index.html?eref=edition', '2015.01.27', 0),
(2, 3, 'cnn.com', 'NYC blizzard in slow motion', 'Ahead of what could be a historic blizzard in the Northeast, people in Times Square still find time to slip and take ''selfies'' in the winter weather.', '/us/nyc-blizzard-in-slow-motion', 'http://edition.cnn.com/video/data/2.0/video/us/2015/01/27/orig-nyc-blizzard-2015-in-slo-motion-times-square.cnn.html?eref=edition', '2015.01.27', 0),
(3, 3, 'cnn.com', 'In pictures: Snow hits U.S.', 'The National Weather Service is using terms like "life-threatening" and "historic" to describe the weather system taking aim at the Northeastern United States.', '/us/in-pictures-snow-hits-us', 'http://edition.cnn.com/2015/01/24/us/gallery/northeast-weather/index.html?eref=edition', '2015.01.27', 0),
(4, 3, 'cnn.com', 'Snow love? Seeking NYC ''blizzard buddies''', 'Forget the bread and milk. Some snowbound New Yorkers are seeking a more, er, intimate kind of nourishment.', '/us/snow-love-seeking-nyc-blizzard-buddies', 'http://edition.cnn.com/2015/01/26/living/blizzard-buddies-craigslist-feat/index.html?eref=edition', '2015.01.27', 0),
(5, 3, 'cnn.com', 'What you need to know about blizzard', 'The first major snowstorm of 2015 has hit the Northeastern United States.', '/us/what-you-need-to-know-about-blizzard', 'http://edition.cnn.com/2015/01/26/us/winter-storm-timeline/index.html?eref=edition', '2015.01.27', 0),
(6, 3, 'cnn.com', 'Gunmen attack Libya hotel', 'Gunmen shot their way into the luxurious Corinthia Hotel in Tripoli on Tuesday, and it wasn''t immediately clear whether there were casualties in the attack. ', '/us/gunmen-attack-libya-hotel', 'http://edition.cnn.com/2015/01/27/middleeast/libya-corinthia-hotel-attack/index.html?eref=edition', '2015.01.27', 0),
(7, 3, 'cnn.com', 'Obama calls for India reform', 'In the final hours of a visit meant to demonstrate the deep societal ties between the United States and India, President Barack Obama briefly broke from his gushing praise for the new Prime Minister to make a soft but undisguised push toward gender equality and religious freedom.', '/us/obama-calls-for-india-reform', 'http://edition.cnn.com/2015/01/27/politics/obama-india-visit/index.html?eref=edition', '2015.01.27', 0),
(8, 3, 'cnn.com', 'Jokowi on Islam, democracy', 'Indonesia''s President Joko Widodo cycles through the crowds with CNN''s Christiane Amanpour and discusses extremism, death penalty and the AirAsia crash. ', '/us/jokowi-on-islam-democracy', 'http://edition.cnn.com/2015/01/26/asia/indonesia-president-joko-widodo-interview/index.html?eref=edition', '2015.01.27', 0),
(9, 3, 'cnn.com', '''Spies'' puzzling activity in NYC', 'The men would sometimes say they needed to meet to exchange tickets, but they never seemed to end up actually attending or discussing a sporting event or a concert.', '/us/spies-puzzling-activity-in-nyc', 'http://edition.cnn.com/2015/01/27/us/new-york-alleged-russian-spy/index.html?eref=edition', '2015.01.27', 0),
(10, 3, 'cnn.com', 'Survivors of Auschwitz return', 'CNN''s Ivan Watson interviews a man returning to Auschwitz for the first time in 70 years since being being a prisoner there.', '/us/survivors-of-auschwitz-return', 'http://edition.cnn.com/video/data/2.0/video/world/2015/01/27/lklv-watson-auschwitz-liberated-anniversary.cnn.html?eref=edition', '2015.01.27', 0),
(11, 3, 'cnn.com', 'Facebook down; Twitter freaks', 'It''s bad enough that the northwest has a horrible storm to contend with, but then Facebook and Instagram goes out?', '/us/facebook-down-twitter-freaks', 'http://edition.cnn.com/2015/01/27/tech/facebook-instagram-down/index.html?eref=edition', '2015.01.27', 0),
(12, 3, 'cnn.com', 'Nadal stunned at Aussie Open', 'This time there was no escape for Rafael Nadal at the Australian Open. ', '/us/nadal-stunned-at-aussie-open', 'http://edition.cnn.com/2015/01/27/tennis/australian-open-tennis-nadal-berdych/index.html?eref=edition', '2015.01.27', 0),
(13, 3, 'cnn.com', 'Indonesia military ends QZ8501 hunt', 'The Indonesian military said Tuesday that it was stopping its efforts to recover the remains of AirAsia Flight QZ8501 almost a month after the commercial jet crashed into the sea. ', '/us/indonesia-military-ends-qz8501-hunt', 'http://edition.cnn.com/2015/01/27/asia/airasia-disaster/index.html?eref=edition', '2015.01.27', 0),
(14, 3, 'cnn.com', 'PM: Greece is leaving austerity', 'leader of the left-wing Syriza party Alexis Tsipras is sworn in as Greece''s new Prime Minister after forming a coalition -- but how will Greece satisfy promises on ending austerity?', '/us/pm-greece-is-leaving-austerity', 'http://edition.cnn.com/2015/01/26/europe/greece-elections/index.html?eref=edition', '2015.01.27', 0),
(15, 3, 'cnn.com', 'Castro supports talks with U.S.', 'A message reported to be from retired Cuban leader Fidel Castro late Monday endorsed the fledgling talks to restore diplomatic relations between Cuba and the United States, but added Castro still "didn''t trust" U.S. officials.', '/us/castro-supports-talks-with-us', 'http://edition.cnn.com/2015/01/27/americas/cuba-castro-message/index.html?eref=edition', '2015.01.27', 0),
(16, 3, 'cnn.com', 'Rebels kill 43 police commandos', 'Forty-three people were killed in intense fighting between police commandos and Muslim insurgents in the southern Philippines Sunday, placing strains on a peace process designed to end decades of conflict in the restive region.', '/us/rebels-kill-43-police-commandos', 'http://edition.cnn.com/2015/01/26/world/philippines-maguindanao-milf-battle/index.html?eref=edition', '2015.01.27', 0),
(17, 3, 'cnn.com', 'U.S. hits Yemen with drone', 'The United States has launched a fresh drone strike on Yemen and closed its embassy to the public, days after the U.S.-backed government crumbled under an uprising from Shiite Houthi rebels.', '/us/us-hits-yemen-with-drone', 'http://edition.cnn.com/2015/01/26/world/yemen-us/index.html?eref=edition', '2015.01.27', 0),
(18, 3, 'cnn.com', 'Japan mulls ISIS hostage strategy', 'ISIS wants a prisoner swap in exchange for the release of Japanese hostage Kenji Goto. CNN''s Will Ripley explains.', '/us/japan-mulls-isis-hostage-strategy', 'http://edition.cnn.com/video/data/2.0/video/world/2015/01/26/pkg-ripley-isis-japan-hostage.cnn.html?eref=edition', '2015.01.27', 0),
(19, 3, 'cnn.com', 'Gift UK minister shouldn''t have given', 'A British transport minister on a trade visit to Taipei got a lesson in the perils of diplomatic gift giving Monday when she presented a pocket watch to the city''s mayor -- a taboo act in Chinese culture.', '/us/gift-uk-minister-shouldnt-have-given', 'http://edition.cnn.com/2015/01/27/asia/taiwan-watch-gaffe/index.html?eref=edition', '2015.01.27', 0),
(20, 3, 'cnn.com', 'White House drone pilot quizzed', 'The U.S. Secret Service is investigating a "device" found on the grounds of the White House, Press Secretary Josh Earnest said Monday morning, adding early indications are that the device does not pose an ongoing threat.', '/us/white-house-drone-pilot-quizzed', 'http://edition.cnn.com/2015/01/26/politics/white-house-device-secret-service/index.html?eref=edition', '2015.01.27', 0),
(21, 3, 'cnn.com', 'Execution set for U.S. disabled man', 'Twice-convicted murderer Warren Lee Hill is set to be executed in Georgia on Tuesday night, despite pleas from human rights groups and legal representatives who say his intellectual disability should make him ineligible for the death penalty.', '/us/execution-set-for-us-disabled-man', 'http://edition.cnn.com/2015/01/26/us/georgia-inmate-tuesday-execution/index.html?eref=edition', '2015.01.27', 0),
(22, 3, 'cnn.com', 'Blatter faces new rival for FIFA job', 'Michael van Praag, the head of Dutch soccer, has joined the race to become FIFA''s next president.', '/us/blatter-faces-new-rival-for-fifa-job', 'http://edition.cnn.com/2015/01/26/football/van-praag-fifa-presidency/index.html?eref=edition', '2015.01.27', 0),
(23, 3, 'cnn.com', 'Gruesome football banner shocks', 'Fans of Belgian football side Standard Liege have been widely condemned after unfurling a banner depicting the decapitation of a former player during a match against league bitter rivals Anderlecht on Sunday.', '/us/gruesome-football-banner-shocks', 'http://edition.cnn.com/2015/01/26/football/football-red-or-dead-banner-standard-liege/index.html?eref=edition', '2015.01.27', 0),
(24, 3, 'cnn.com', 'Strange blue glow lights harbor', '', '/us/strange-blue-glow-lights-harbor', 'http://edition.cnn.com/2015/01/26/asia/hong-kong-blue-algae/index.html?eref=edition', '2015.01.27', 0),
(25, 3, 'cnn.com', 'Asteroid''s moon seen in Earth flyby', 'The asteroid that flew close to Earth Monday didn''t come alone.', '/us/asteroids-moon-seen-in-earth-flyby', 'http://edition.cnn.com/2015/01/26/us/asteroid-flyby/index.html?eref=edition', '2015.01.27', 0),
(26, 3, 'cnn.com', 'I had to dance for Nazi''s ''Angel of Death''', '', '/us/i-had-to-dance-for-nazis-angel-of-death', 'http://edition.cnn.com/2015/01/25/world/auschwitz-dancing-mengele/index.html?eref=edition', '2015.01.27', 0),
(27, 3, 'cnn.com', 'Drone video shows scale of Auschwitz camp', 'Since its liberation in January 1945, Auschwitz has become a symbol of the atrocities of the Holocaust.', '/us/drone-video-shows-scale-of-auschwitz-camp', 'http://edition.cnn.com/video/data/2.0/video/world/2015/01/21/orig-drone-footage-auschwitz-camp-nazi.cnn.html?eref=edition', '2015.01.27', 0),
(28, 3, 'cnn.com', '''One direction meant life, the other one meant death''', 'Rozalia Wolf was only 15 years old when the horror began. While most young girls worry about boys and homework, Rozalia Wolf spent her teenage days fearing she would not live to see the sun rise again. She spent a lifetime trying forget the horrors she had to endure at Auschwitz. This year she is turning 91 and for the first time she shares her story and tries to make sense of why she survived when so many others did not. ', '/us/one-direction-meant-life-the-other-one-meant-death', 'http://edition.cnn.com/2015/01/27/europe/auschwitz-survivor-rozalia/index.html?eref=edition', '2015.01.27', 0),
(29, 3, 'cnn.com', 'In photos: Auschwitz liberated', '', '/us/in-photos-auschwitz-liberated', 'http://edition.cnn.com/2015/01/23/world/gallery/auschwitz-liberation/index.html?eref=edition', '2015.01.27', 0),
(30, 3, 'cnn.com', 'Why nudity doesn''t shock us anymore', '', '/us/why-nudity-doesnt-shock-us-anymore', 'http://edition.cnn.com/2015/01/25/opinion/drexler-paris-fashion-shock/index.html?eref=edition', '2015.01.27', 0),
(31, 3, 'cnn.com', 'Why was AirAsia jet the only one in trouble?', '', '/us/why-was-airasia-jet-the-only-one-in-trouble', 'http://edition.cnn.com/2015/01/26/asia/indonesia-airasia-transportation-minister/index.html?eref=edition', '2015.01.27', 0),
(32, 3, 'cnn.com', 'Nadal exits Australian Open', '', '/us/nadal-exits-australian-open', 'http://edition.cnn.com/2015/01/27/tennis/australian-open-tennis-nadal-berdych/index.html?eref=edition', '2015.01.27', 0),
(33, 3, 'cnn.com', 'World''s scariest rides', '', '/us/worlds-scariest-rides', 'http://edition.cnn.com/2015/01/27/travel/scariest-theme-park-rides/index.html?eref=edition', '2015.01.27', 0),
(34, 3, 'cnn.com', 'The world''s most beautiful watches ', '', '/us/the-worlds-most-beautiful-watches', 'http://edition.cnn.com/2015/01/24/world/sihh-luxury-watches/index.html?eref=edition', '2015.01.27', 0),
(35, 3, 'cnn.com', 'The best of Asian street style', 'Street style photographer James Bent photographs the continent''s most fashionable pedestrians. ', '/us/the-best-of-asian-street-style', 'http://edition.cnn.com/2015/01/19/asia/gallery/the-best-of-asian-street-style/index.html?eref=edition', '2015.01.27', 0),
(36, 3, 'cnn.com', 'ISIS loses battle for Kobani', 'ISIS is calling for more attacks on the West after it suffered a major defeat on the battle field in Kobani. CNN''s Jim Sciutto reports.', '/us/isis-loses-battle-for-kobani', 'http://edition.cnn.com/video/data/2.0/video/world/2015/01/26/tsr-dnt-sciutto-isis-kobani.cnn.html?eref=edition', '2015.01.27', 0),
(37, 3, 'cnn.com', 'India displays military might', 'President Obama attended the Indian Republic Day Parade where the country''s armed forces are showcased.', '/us/india-displays-military-might', 'http://edition.cnn.com/video/data/2.0/video/world/2015/01/26/orig-india-obama-republic-parade-military.cnn.html?eref=edition', '2015.01.27', 0),
(38, 3, 'cnn.com', 'News anchor reveals ALS struggle in emotional video', 'In an emotional video, WTVD news anchor Larry Stogner revealed to North Carolina viewers that he is struggling with ALS and will be stepping down.', '/us/news-anchor-reveals-als-struggle-in-emotional-video', 'http://edition.cnn.com/video/data/2.0/video/us/2015/01/27/sot-news-anchor-reveals-als-struggle.wtvd.html?eref=edition', '2015.01.27', 0),
(39, 3, 'cnn.com', '''Shake It Off'' cop strikes again', '"Shake It Off" cop dances with handcuffed women. CNN''s Jeanne Moos has the sequel.', '/us/shake-it-off-cop-strikes-again', 'http://edition.cnn.com/video/data/2.0/video/us/2015/01/26/pkg-moos-dancing-cop-sequel.cnn.html?eref=edition', '2015.01.27', 0),
(40, 3, 'cnn.com', 'How zoo animals survive a blizzard ', 'The heads of two Northeast zoo''s explain how they keep their animals safe during extreme weather conditions. ', '/us/how-zoo-animals-survive-a-blizzard', 'http://edition.cnn.com/video/data/2.0/video/weather/2015/01/27/pkg-how-zoo-animals-survive-a-blizzard.cnn.html?eref=edition', '2015.01.27', 0),
(41, 3, 'yelp.com', 'Susie Y.''s Review of &Hair Lounge - New York (5/5) on Yelp', 'Great digital perm by Mavis. Its very natural looking and she talked me through the entire process.', '/us/susie-ys-review-of-hair-lounge-new-york-(55)-on-yelp', 'http://www.yelp.com/biz/and-hair-lounge-new-york-7?hrid=pIWfFozGmHhIJo3wZ2zBSQ', '2015.01.27', 0),
(42, 3, 'yelp.com', 'John C.''s Review of Jarets Stuffed Cupcakes - Nutley (5/5) on Yelp', 'Jarets Stuffed Cupcakes is simply divine.  My favorite is the classic red velvet.  It''s also great to meet the owner when you walk in, both her and her husband are were excited to be opening a new…', '/us/john-cs-review-of-jarets-stuffed-cupcakes-nutley-(55)-on-yelp', 'http://www.yelp.com/biz/jarets-stuffed-cupcakes-nutley?hrid=9BTVIAs-T6iEBb1rkaMxCw', '2015.01.27', 0),
(43, 3, 'yelp.com', 'Arpit J.''s Review of Potjanee Thai Restaurant - New York (5/5) on Yelp', 'Excellent food. Thai dumplings recommended.', '/us/arpit-js-review-of-potjanee-thai-restaurant-new-york-(55)-on-yelp', 'http://www.yelp.com/biz/potjanee-thai-restaurant-new-york?hrid=IQ2WqRX4VE-Da6dWZoachw', '2015.01.27', 0),
(44, 3, 'yelp.com', 'Terrance P.''s Review of Frankie & Johnnie''s Steak House - New York (5/5) on Yelp', 'This is my spot. Great atmosphere and friendly russian bartenders.', '/us/terrance-ps-review-of-frankie-johnnies-steak-house-new-york-(55)-on-yelp', 'http://www.yelp.com/biz/frankie-and-johnnies-steak-house-new-york?hrid=R5FFlvwBmh02ug85-7Hrlg', '2015.01.27', 0),
(45, 3, 'yelp.com', 'Arpit J.''s Review of Max Brenner - New York (5/5) on Yelp', 'I find the pasta and pizza better than desserts.\nSunday Mood pasta is amazing.', '/us/arpit-js-review-of-max-brenner-new-york-(55)-on-yelp', 'http://www.yelp.com/biz/max-brenner-new-york?hrid=YIowJZBX3IloDWFLU-PKqA', '2015.01.27', 0),
(46, 3, 'yelp.com', 'Leonardo S.''s Review of Sociale - Brooklyn (5/5) on Yelp', 'During our visit in Brooklyn Heights we noticed this cosy and cool restaurant, we understood was italian because of it''s name "SOCIALE", that in italian it means social, people, stay together...once…', '/us/leonardo-ss-review-of-sociale-brooklyn-(55)-on-yelp', 'http://www.yelp.com/biz/sociale-brooklyn?hrid=1mQFLml10lZhGcYEAOXGSg', '2015.01.27', 0),
(47, 3, 'yelp.com', 'Aaron A.''s Review of Umami Burger - New York (4/5) on Yelp', 'This place is delicious. And this is coming from someone who doesn''t normally eat burgers!', '/us/aaron-as-review-of-umami-burger-new-york-(45)-on-yelp', 'http://www.yelp.com/biz/umami-burger-new-york?hrid=DO_L_lS8Be5sLA-RCTDOHA', '2015.01.27', 0),
(48, 3, 'yelp.com', 'Marjorie S.''s Review of Umami Burger - New York (4/5) on Yelp', 'Excellent restaurant! Creative burgers and appetizers, quick and friendly service.', '/us/marjorie-ss-review-of-umami-burger-new-york-(45)-on-yelp', 'http://www.yelp.com/biz/umami-burger-new-york?hrid=WLTWJEO1gyXnKJPwO5bVEA', '2015.01.27', 0),
(49, 3, 'yelp.com', 'Joseph V.''s Review of Arsen''s Barber Shop 1 - Forest Hills (5/5) on Yelp', '5 stars across the board easily.\n\nPerfect service.\n\nHidden Gem.\n\nThe earlier you go, the better because you could be waiting a while for Greg. And he engages in conversation with you and genuinely…', '/us/joseph-vs-review-of-arsens-barber-shop-1-forest-hills-(55)-on-yelp', 'http://www.yelp.com/biz/arsens-barber-shop-1-forest-hills?hrid=J-gS4U8iZHaNHQLIvBWFCg', '2015.01.27', 0),
(50, 3, 'yelp.com', 'Dawn P.''s Review of Olympus Moving & Storage - Brooklyn (4/5) on Yelp', 'I was susceptible on moving my mom''s expensive glassware and china cutlery when moving house. Working with a magazine means I have to shift offices on a regular basis, and this time my mom was also…', '/us/dawn-ps-review-of-olympus-moving-storage-brooklyn-(45)-on-yelp', 'http://www.yelp.com/biz/olympus-moving-and-storage-brooklyn?hrid=0P9ppRY3EIJ8X1yVOf6mug', '2015.01.27', 0),
(51, 3, 'yelp.com', 'Linda B.''s Review of Domino''s Pizza - New York (5/5) on Yelp', 'It is great that domminos offers gluten free pizza not everyone wants regular pizza or not everyone can have it I dont have a problem with regular pizza however I perfer gluten free it is so much…', '/us/linda-bs-review-of-dominos-pizza-new-york-(55)-on-yelp', 'http://www.yelp.com/biz/dominos-pizza-new-york-9?hrid=hSgIwzqm7dkcPZ1Darzh0Q', '2015.01.27', 0),
(52, 3, 'yelp.com', 'Olga T.''s Review of MatchPoint NYC - Brooklyn (3/5) on Yelp', 'Very nice place but they need to lower the price to use their tennis courts, get bigger towels and make the women''s locker room more secure because you can see everything!!!!', '/us/olga-ts-review-of-matchpoint-nyc-brooklyn-(35)-on-yelp', 'http://www.yelp.com/biz/matchpoint-nyc-brooklyn?hrid=DFYrNdWxW2xT7VzdsIp2RQ', '2015.01.27', 0),
(53, 3, 'yelp.com', 'Mike D.''s Review of ECRB Towing and Recovery - Bloomfield (1/5) on Yelp', 'Rude, the dregs of society. Go out of your way to avoid these people. They are the complete opposite of there mission statement. They are there to scam your money and that''s all.', '/us/mike-ds-review-of-ecrb-towing-and-recovery-bloomfield-(15)-on-yelp', 'http://www.yelp.com/biz/e-c-r-b-towing-and-recovery-bloomfield?hrid=f7M3LO3DLENGaY7lw2ui2g', '2015.01.27', 0),
(54, 3, 'yelp.com', 'Michael T.''s Review of Sushi Nakazawa - New York (3/5) on Yelp', 'There was a lot of hype surrounding Sushi Nakazawa with their head chef being the apprentice of legendary Jiro Yoshino of "Jiro Dreams of Sushi" fame.  My friends and I would get super excited just…', '/us/michael-ts-review-of-sushi-nakazawa-new-york-(35)-on-yelp', 'http://www.yelp.com/biz/sushi-nakazawa-new-york?hrid=VE1mdMP5hcQW9H605NdqNw', '2015.01.27', 0),
(55, 3, 'yelp.com', 'Myles M.''s Review of Thompson Norris Home Improvements - Staten Island (5/5) on Yelp', 'Home Improvement, Kitchen Remodeling, Flooring', '/us/myles-ms-review-of-thompson-norris-home-improvements-staten-island-(55)-on-yelp', 'http://www.yelp.com/biz/thompson-norris-home-improvements-staten-island?hrid=o1tNSvKODuwlhGBKAYDxlg', '2015.01.27', 0),
(56, 3, 'yelp.com', 'Jessica F.''s Review of Tomcats Barbershop - Brooklyn (5/5) on Yelp', 'Great vibe! Owen and Veronica have worked on my hair..I can say this. .they know what they are doing. This isn''t a crew that learned clipper work and try to figure out the stylist scissor part which…', '/us/jessica-fs-review-of-tomcats-barbershop-brooklyn-(55)-on-yelp', 'http://www.yelp.com/biz/tomcats-barbershop-brooklyn?hrid=duqXvw0WfZFjecWPBDfv5w', '2015.01.27', 0),
(57, 3, 'yelp.com', 'Nat S.''s Review of Copyland Center, Inc - New York (5/5) on Yelp', 'Helpful and efficient staff, open late, cheaper than most other places in the area and always does a meticulous job. Great local business.', '/us/nat-ss-review-of-copyland-center-inc-new-york-(55)-on-yelp', 'http://www.yelp.com/biz/copyland-center-inc-new-york?hrid=d9MT9JQeNnJtnrrTYg_JJA', '2015.01.27', 0),
(58, 3, 'yelp.com', 'Jeff H.''s Review of The Halal Guys - New York (2/5) on Yelp', 'Halal guys is a certified Manhattan hotspot. It''s one of those places you try just to say you''ve tried it. Just make sure your expectations are at the right level: okay food, but you''ll wait a while…', '/us/jeff-hs-review-of-the-halal-guys-new-york-(25)-on-yelp', 'http://www.yelp.com/biz/the-halal-guys-new-york-2?hrid=QB3YG9RG8OQZgBSWYbQPyg', '2015.01.27', 0),
(59, 3, 'yelp.com', 'Mo A.''s Review of Pal Supermarket - Brooklyn (5/5) on Yelp', 'Great selection of organic food & beer. Also the deli have so many options to choose from. Service is pleasant and helpful and prices are good, compare to other organic stores. Go shop at Pal…', '/us/mo-as-review-of-pal-supermarket-brooklyn-(55)-on-yelp', 'http://www.yelp.com/biz/pal-supermarket-brooklyn-3?hrid=WWyc7HYnKjO0tny_4CH0EA', '2015.01.27', 0),
(60, 3, 'yelp.com', 'Juan F.''s Review of White Star at Harbor - Jersey City (5/5) on Yelp', 'I come here every Tuesday night just to hang with Sherry, one of America''s best bartenders; whether anyone else I know is in there or not. Her drinks are great,  the beer selection is good and the…', '/us/juan-fs-review-of-white-star-at-harbor-jersey-city-(55)-on-yelp', 'http://www.yelp.com/biz/white-star-at-harbor-jersey-city?hrid=PFEA_snOTTXJJY2IOb07PA', '2015.01.27', 0),
(61, 3, 'yelp.com', 'Sarah L.''s Review of Pies-n-Thighs - Brooklyn (4/5) on Yelp', 'Cute place. Haven''t sat in one of those elementary school chairs in a while! Chicken was delicious as expected. The cheese grits (-lite) fell a little flat; expected more buttery fatness. Pies were a…', '/us/sarah-ls-review-of-piesnthighs-brooklyn-(45)-on-yelp', 'http://www.yelp.com/biz/pies-n-thighs-brooklyn?hrid=RMuthQE5xq-crR4RLpGGNA', '2015.01.27', 0),
(62, 3, 'yelp.com', 'Monique C.''s Review of Buttercup Bake Shop - New York (5/5) on Yelp', 'Devil Dog Cupcake.  That is all.', '/us/monique-cs-review-of-buttercup-bake-shop-new-york-(55)-on-yelp', 'http://www.yelp.com/biz/buttercup-bake-shop-new-york-6?hrid=xToqu4Nv6-8-L1Rh_zkeew', '2015.01.27', 0),
(63, 3, 'yelp.com', 'Snow G.''s Review of Lombardi''s Pizza - New York (3/5) on Yelp', 'Good pizza. Lots of tourists. Small tables. Long line. Too pricy fot pizza.', '/us/snow-gs-review-of-lombardis-pizza-new-york-(35)-on-yelp', 'http://www.yelp.com/biz/lombardis-pizza-new-york?hrid=CDvHSsK8MlUbQvxSJrLqnQ', '2015.01.27', 0),
(64, 4, 'gandul.info', 'SENTINŢĂ în dosarul privatizărilor strategice. Codruţ Şereş, 4 ani şi 8 luni cu EXECUTARE, Nagy Zsolt - 4 ani', 'Completul de cinci judecători conduşi de către vicepreşedintele Curţii Supreme, Ionuţ Matei, va pronunţa astăzi sentinţa în dosarul în care sunt inculpaţi foştii miniştri Codruţ Şereş şi Nagy Zsolt. Pe fond, cei doi au primit şase, respectiv cinci ani de închisoare cu executare. Ei sunt acuzaţi de DIICOT de trădare, pentru că ar fi oferit informaţii clasificate unor operatori privaţi în procesele de privatizare a mai multor companii de stat. Principalele soluţii pe care le poate pronunţa instanţa sunt: achitarea (cei doi scapă de închisoare), respingerea apelurilor şi menţinerea soluţiei de fond (cei doi rămân cu pedepsele date pe fond) sau chiar mărirea pedepselor pentru inculpraţi în rejudecare.\n												\n						\n						\n											', '/ro/sentinta-in-dosarul-privatizarilor-strategice-codrut-seres-4-ani-si-8-luni-cu-executare-nagy-zsolt-4-ani', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Z64sW195asc/sentinta-in-dosarul-privatizarilor-strategice-codrut-seres-4-ani-si-8-luni-cu-executare-nagy-zsolt-4-ani-13787478', '2015.01.27', 0),
(65, 4, 'gandul.info', 'Justiţia şi partidele dau marele test. CINCI „REŢETE” prin care se scurg milioane de euro din bani publici în campaniile electorale', 'Înainte ca finanţarea partidelor să fie miercuri subiect al consultărilor de la Palatul Cotroceni, Gândul reconstituie astăzi situaţiile concrete de "scurgere" a banilor electorali, datorită fisurilor legii, pe care le-a demonstrat pe parcursul campaniei prezidenţiale.\n												\n						\n						\n											', '/ro/justitia-si-partidele-dau-marele-test-cinci-retete-prin-care-se-scurg-milioane-de-euro-din-bani-publici-in-campaniile-electorale', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/PPPpGwSLXHg/justitia-si-partidele-dau-marele-test-cinci-retete-prin-care-se-scurg-milioane-de-euro-din-bani-publici-in-campaniile-electorale-13784946', '2015.01.27', 0),
(66, 4, 'gandul.info', 'De când nu mai e ora de religie  "obligatorie" în şcoli. Ce spune ministrul Educaţiei', 'Ministrul Educaţiei, Mihai Sorin Câmpeanu, a declarat, luni, la Vaslui, că decizia Curţii Constituţionale privind neconstituţionalitatea obligaţiei de a face cerere pentru a nu participa la ora de religie nu poate fi aplicată retroactiv, astfel încât aceasta va intra în vigoare din septembrie 2015.\n												\n						\n						\n											', '/ro/de-cand-nu-mai-e-ora-de-religie-obligatorie-in-scoli-ce-spune-ministrul-educatiei', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/RK6ujBruW2g/de-cand-nu-mai-e-ora-de-religie-obligatorie-in-scoli-ce-spune-ministrul-educatiei-13787908', '2015.01.27', 0),
(67, 4, 'gandul.info', 'Prima REACŢIE a Simonei Halep după înfrîngere: ce s-a întâmplat înaintea meciului', 'Jucătoarea de tenis Simona Halep, cap de serie numărul 3 şi locul 3 WTA, a declarat, marţi, după eliminarea din sferturile de finală de la Australian Open, că a fost puţin stresată înaintea meciului cu rusoaica Ekaterina Makarova, informează site-ul wtatennis.com.\n												\n						\n						\n											', '/ro/prima-reactie-a-simonei-halep-dupa-infringere-ce-sa-intamplat-inaintea-meciului', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/84JbUMAE7r0/prima-reactie-a-simonei-halep-dupa-infringere-ce-s-a-intamplat-inaintea-meciului-13787675', '2015.01.27', 0),
(68, 4, 'gandul.info', 'Ponta duce PSD în „team-building” la munte. A invitat la un hotel toţi parlamentarii, şefii de Consilii Judeţene şi primarii: CRIZELE pe care trebuie să le stingă premierul', 'Criză în PSD\n												\n						\n						\n											', '/ro/ponta-duce-psd-in-teambuilding-la-munte-a-invitat-la-un-hotel-toti-parlamentarii-sefii-de-consilii-judetene-si-primarii-crizele-pe-care-trebuie-sa-le-stinga-premierul', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Ox64XrjP1DI/ponta-duce-psd-in-team-building-la-munte-a-invitat-la-un-hotel-toti-parlamentarii-sefii-de-consilii-judetene-si-primarii-crizele-pe-care-trebuie-sa-le-stinga-premierul-13785135', '2015.01.27', 0),
(69, 4, 'gandul.info', 'Curtea Supremă a respins recursul în casaţie al lui Dan Voiculescu. Fondatorul Grivco nu mai are căi de atac în ţară', 'Dan Voiculescu rămâne cu condamnarea de 10 ani de închisoare primită în dosarul ICA, după ce a pierdut şi ultima cale de atac. Recursul în casaţie al fondatorului PC a fost respins, marţi.\n												\n						\n						\n											', '/ro/curtea-suprema-a-respins-recursul-in-casatie-al-lui-dan-voiculescu-fondatorul-grivco-nu-mai-are-cai-de-atac-in-tara', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/K3ZLdlVBKHE/curtea-suprema-a-respins-recursul-in-casatie-al-lui-dan-voiculescu-fondatorul-grivco-nu-mai-are-cai-de-atac-in-tara-13787679', '2015.01.27', 0),
(70, 4, 'gandul.info', 'Tribunalul Ilfov: Sorin Ovidiu Vîntu a fost eliberat pentru că a dat dovezi de îndreptare şi regretă sincer fapta', 'Sorin Ovidiu Vîntu a fost eliberat condiţionat pentru că s-a conformat rigorilor detenţiei, a dat dovezi de îndreptare şi a îndeplinit cu responsabilitate toate sarcinile, arătând că "regretă sincer fapta pentru care a fost încarcerat", potrivit motivării deciziei Tribunalului Ilfov. \n												\n						\n						\n											', '/ro/tribunalul-ilfov-sorin-ovidiu-vintu-a-fost-eliberat-pentru-ca-a-dat-dovezi-de-indreptare-si-regreta-sincer-fapta', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/3I-bKsCXhsA/tribunalul-ilfov-sorin-ovidiu-vintu-a-fost-eliberat-pentru-ca-a-dat-dovezi-de-indreptare-si-regreta-sincer-fapta-13788081', '2015.01.27', 0),
(71, 4, 'gandul.info', 'Recomandarea primită azi de televiziuni din partea CNA', 'Consiliul Naţional al Audiovizualului (CNA) recomandă televiziunilor să difuzeze şapte spoturi animate care conţin informaţii referitoare la măsurile ce trebuie să fie adoptate şi la comportamentul adecvat înainte de producerea, pe timpul şi după manifestarea unui cutremur.\n												\n						\n						\n											', '/ro/recomandarea-primita-azi-de-televiziuni-din-partea-cna', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/NHwr0Sw08Eo/recomandarea-primita-azi-de-televiziuni-din-partea-cna-13788045', '2015.01.27', 0),
(72, 4, 'gandul.info', 'România, condamnată din nou la CEDO: are de plătit 832.500 euro către 81 de victime ale Revoluţiei', 'România a fost condamnată din nou de Curtea Europeană a Drepturilor Omului (CEDO) pentru nesoluţionarea "dosarului Revoluţiei", având de plătit de această dată suma de 832.500 euro către 81 de persoane.\n												\n						\n						\n											', '/ro/romania-condamnata-din-nou-la-cedo-are-de-platit-832500-euro-catre-81-de-victime-ale-revolutiei', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/umCwOM5pHeg/romania-condamnata-din-nou-la-cedo-are-de-platit-832-500-euro-catre-81-de-victime-ale-revolutiei-13788088', '2015.01.27', 0),
(73, 4, 'gandul.info', 'Ţara în care un litru de benzină costă 0,0005 dolari', 'Preţul unui galon (3,78 litri) de benzină a ajuns în Venezuela la echivalentul a 0,002 dolari, ceea ce înseamnă că 1 dolar este suficient pentru a cumpăra aproape 2.000 de litri de benzină, scrie Bloomberg.\n												\n						\n						\n											', '/ro/tara-in-care-un-litru-de-benzina-costa-00005-dolari', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/-gmYTxCRlBg/tara-in-care-un-litru-de-benzina-costa-0-0005-dolari-13787487', '2015.01.27', 0),
(74, 4, 'gandul.info', 'Delegaţia FMI începe vizita în România cu discuţii la BNR', 'Reprezentanţii delegaţiei FMI se află la BNR, printre temele discutate cu guvernatorul Mugur Isărescu numărându-se legea insolvenţei personale şi conversia creditelor.\n												\n						\n						\n											', '/ro/delegatia-fmi-incepe-vizita-in-romania-cu-discutii-la-bnr', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/vdOwWCZwXMU/delegatia-fmi-incepe-vizita-in-romania-cu-discutii-la-bnr-13787764', '2015.01.27', 0),
(75, 4, 'gandul.info', 'Operaţiune anti-jihadistă în Franţa: cinci persoane au fost arestate', 'Cinci persoane au fost arestate, marţi dimineaţă, în Franţa, într-o operaţiune anti-jihadistă, care a avut loc la Lunel (sud), un oraş din care se crede că zeci de tineri s-au alăturat recent unor grupări teroriste, informează Le Figaro. Cei cinci sunt suspectaţi că au legături cu jihadiştii din Irak şi Siria, adaugă sursa. O persoană a fost rănită în această operaţiune, presa locală scriind că este vorba despre un localnic.\n												\n						\n						\n											', '/ro/operatiune-antijihadista-in-franta-cinci-persoane-au-fost-arestate', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/-8UbvYySOFw/operatiune-anti-jihadista-in-franta-cinci-persoane-au-fost-arestate-13787691', '2015.01.27', 0),
(76, 4, 'gandul.info', 'Simona Halep învinsă clar, în sferturi, la Australian Open. Cristian Tudor Popescu: Simona s-a topit. Cum se numeşte ASTA în tenis', 'Jucătoarea Simona Halep, locul 3 WTA şi a treia favorită, a fost învinsă, marţi, cu scorul de 6-4, 6-0, de rusoaica Ekaterina Makarova, locul 11 WTA şi cap de serie numărul 10, în sferturile de finală ale Australian Open, primul turneu de Grand Slam al anului. Dincolo de eliminare, a surprins jocul Simonei Halep, care a intrat crispată pe teren şi a greşit foarte mult. Editorialistul Gândul, Cristian Tudor Popescu, a comentat la cald meciul, constatând că ce i s-a întâmplat Simonei „se numeşte în tenis to be out of the game”.\n\n												\n						\n						\n											', '/ro/simona-halep-invinsa-clar-in-sferturi-la-australian-open-cristian-tudor-popescu-simona-sa-topit-cum-se-numeste-asta-in-tenis', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Nipyv34DLhI/simona-halep-invinsa-clar-in-sferturi-la-australian-open-cristian-tudor-popescu-simona-s-a-topit-cum-se-numeste-asta-in-tenis-13787540', '2015.01.27', 0),
(77, 4, 'gandul.info', 'Reacţia CNADNR, după ce un fost director a fost reclamat la DNA pentru corupţie şi conflict de interese', 'CNADNR vrea să găsească "modalităţile legale" de încetare a unui contract de lucrări de marcaje rutiere încheiat cu o asociere din care face parte o firmă a fratelui lui Răzvan Emil Teodorescu, fost director în cadrul Companiei de Drumuri, reclamat la DNA pentru corupţie şi conflict de interese.\n												\n						\n						\n											', '/ro/reactia-cnadnr-dupa-ce-un-fost-director-a-fost-reclamat-la-dna-pentru-coruptie-si-conflict-de-interese', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Mf5MT3ow8mg/reactia-cnadnr-dupa-ce-un-fost-director-a-fost-reclamat-la-dna-pentru-coruptie-si-conflict-de-interese-13787760', '2015.01.27', 0),
(78, 4, 'gandul.info', 'FACEBOOK A PICAT. Reţeaua socială A CĂZUT în această dimineaţă întreaga lume. UPDATE: Reţeaua de socializare şi-a revenit după aproximativ o oră', 'Facebook a picat în această dimineaţă în întreaga lume.\n												\n						\n						\n											', '/ro/facebook-a-picat-reteaua-sociala-a-cazut-in-aceasta-dimineata-intreaga-lume-update-reteaua-de-socializare-sia-revenit-dupa-aproximativ-o-ora', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/ADtPmdI5S-U/facebook-a-picat-reteaua-sociala-a-cazut-in-aceasta-dimineata-intreaga-lume-update-reteaua-de-socializare-si-a-revenit-dupa-aproximativ-o-ora-13787505.html', '2015.01.27', 0),
(79, 4, 'gandul.info', 'Aflată la un pas de recesiune, Rusia primeşte o nouă lovitură din partea S&P', 'Agenţia de evaluare financiară Standard&Poor’s (S&P) a scăzut cu o treaptă ratingul de credit al Rusiei, la BB+, cu perspectivă negativă, în categoria nerecomandată pentru investiţii, pentru prima oară în ultimii peste zece ani, transmite Bloomberg.\n												\n						\n						\n											', '/ro/aflata-la-un-pas-de-recesiune-rusia-primeste-o-noua-lovitura-din-partea-sp', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/vy0eNegwWNU/aflata-la-un-pas-de-recesiune-rusia-primeste-o-noua-lovitura-din-partea-s-p-13787882', '2015.01.27', 0),
(80, 4, 'gandul.info', 'Francul elveţian s-a depreciat faţă de euro pe parcursul nopţii. Ce s-a întâmplat cu leul', 'Francul elveţian s-a depreciat pe parcursul nopţii în raport cu euro pe pieţele externe şi rămâne sub paritate, cu un curs calculat la aproximativ 4,4 lei, în timp ce leul s-a întărit uşor în faţa euro, pe volume reduse în piaţa interbancară locală.\n												\n						\n						\n											', '/ro/francul-elvetian-sa-depreciat-fata-de-euro-pe-parcursul-noptii-ce-sa-intamplat-cu-leul', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/7g3tGnCVEYY/francul-elvetian-s-a-depreciat-fata-de-euro-pe-parcursul-noptii-ce-s-a-intamplat-cu-leul-13787753', '2015.01.27', 0),
(81, 4, 'gandul.info', 'Recomandările Inspectoratului pentru Situaţii de Urgenţă în cazul unui cutremur puternic', 'IGSU avertizează într-un ghid de protecţie în caz de cutremur că oamenii trebuie să aibă în permanenţă în locuinţă provizii de apă, hrană uscată, bandaje şi medicamente, pentru a putea supravieţui o perioadă mai lungă de timp, în cazul în care sunt prinşi sub dărâmături.\n												\n						\n						\n											', '/ro/recomandarile-inspectoratului-pentru-situatii-de-urgenta-in-cazul-unui-cutremur-puternic', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/IvHWQB58Xn4/recomandarile-inspectoratului-pentru-situatii-de-urgenta-in-cazul-unui-cutremur-puternic-13787538', '2015.01.27', 0),
(82, 4, 'gandul.info', 'François Hollande a discutat cu preşedintele rus şi cancelarul german despre situaţia din Ucraina', 'Preşedintele francez François Hollande, "foarte îngrijorat" de degradarea situaţiei în Ucraina, a avut discuţii succesive, luni seara, prin telefon cu preşedintele rus Vladimir Putin şi cancelarul german Angela Merkel, a anunţat Palatul Elysée, relatează AFP.  \n												\n						\n						\n											', '/ro/francois-hollande-a-discutat-cu-presedintele-rus-si-cancelarul-german-despre-situatia-din-ucraina', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Rzm7AbxrDTQ/fran-ois-hollande-a-discutat-cu-presedintele-rus-si-cancelarul-german-despre-situatia-din-ucraina-13787567', '2015.01.27', 0),
(83, 4, 'gandul.info', 'Fidel Castro vorbeşte pentru prima dată despre apropierea Cubei de Statele Unite: "Nu am încredere în politica lor, dar..."', 'Fostul preşedinte cubanez Fidel Castro a rupt tăcerea, luni, după mai multe luni recunoscând într-o scrisoare că nu are încredere în Statele Unite, dar că nu respinge totuşi apropierea recentă de Washington, relatează AFP.  \n												\n						\n						\n											', '/ro/fidel-castro-vorbeste-pentru-prima-data-despre-apropierea-cubei-de-statele-unite-nu-am-incredere-in-politica-lor-dar', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/ZNxjC9Vqtpc/fidel-castro-vorbeste-pentru-prima-data-despre-apropierea-cubei-de-statele-unite-nu-am-incredere-in-politica-lor-dar-13787545', '2015.01.27', 0),
(84, 4, 'gandul.info', 'Al Qaida în Peninsula Arabă revendică oficial atacul de la Charlie Hebdo, în raportul trimestrial: ''''Am desfăşurat 204 operaţiuni în Yemen şi un atac în Franţa''''', 'Al-Qaida în Peninsula Arabă (AQPA) a publicat un raport trimestrial al activităţilor sale, afirmând că a desfăşurat 204 operaţiuni în Yemen şi un atac în Franţa împotriva revistei Charlie Hebdo, a anunţat marţi centrul american de supraveghere a site-urilor islamiste, SITE, relatează AFP. \n												\n						\n						\n											', '/ro/al-qaida-in-peninsula-araba-revendica-oficial-atacul-de-la-charlie-hebdo-in-raportul-trimestrial-am-desfasurat-204-operatiuni-in-yemen-si-un-atac-in-franta', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/5p0Wh2IWYBM/al-qaida-in-peninsula-araba-revendica-oficial-atacul-de-la-charlie-hebdo-in-raportul-trimestrial-am-desfasurat-204-operatiuni-in-yemen-si-un-atac-in-franta-13787490', '2015.01.27', 0),
(85, 4, 'gandul.info', 'Minerii de la Exploatarea de Uraniu Crucea continuă protestele', 'Minerii de la Exploatarea de Uraniu din localitatea suceveană Crucea continuă, marţi, protestele declanşate cu o zi în urmă, la ora transmiterii acestei ştiri în faţa sediului sucursalei fiind adunaţi aproximativ 400 de angajaţi ai societăţii, transmite corespondentul MEDIAFAX.\n												\n						\n						\n											', '/ro/minerii-de-la-exploatarea-de-uraniu-crucea-continua-protestele', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/HUvJ3hP-moY/minerii-de-la-exploatarea-de-uraniu-crucea-continua-protestele-13787632', '2015.01.27', 0),
(86, 4, 'gandul.info', 'TRAGERE LA SORŢI CUPA LIGII SEMIFINALE. Steaua - Astra şi Pandurii - Dinamo, în semifinale', 'TRAGERE LA SORŢI CUPA LIGII SEMIFINALE. Echipa Steaua Bucureşti va întâlni Astra Giurgiu, iar Pandurii Târgu Jiu va juca împotriva formaţiei Dinamo Bucureşti, în semifinalele Cupei Ligii Adeplast, s-a stabilit, marţi, în urma tragerii la sorţi efectuată la sediul LPF.\n										\n					\n					\n									', '/ro/tragere-la-sorti-cupa-ligii-semifinale-steaua-astra-si-pandurii-dinamo-in-semifinale', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/3g_KZCX-sJE/tragere-la-sorti-cupa-ligii-semifinale-steaua-astra-si-pandurii-dinamo-in-semifinale-13787665.html', '2015.01.27', 0),
(87, 4, 'gandul.info', 'Cum a reuşit un student chiulangiu din Cluj să dezvolte în Silicon Valley „Instagramul” viitorului', 'După cum chiar el spune, Rusu chiulea de la cursuri în facultate şi „chefuia la greu” între sesiuni.\n										\n					\n					\n									', '/ro/cum-a-reusit-un-student-chiulangiu-din-cluj-sa-dezvolte-in-silicon-valley-instagramul-viitorului', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/N-ANJxp71Ek/cum-a-reusit-un-student-chiulangiu-din-cluj-sa-dezvolte-in-silicon-valley-instagramul-viitorului-13787932', '2015.01.27', 0),
(88, 4, 'gandul.info', 'Facebook şi Instagram nu au funcţionat în dimineaţa zilei de marţi. Cine a revendicat „un atac online” asupra reţelelor de socializare', 'Mai multe site-uri importante, precum Facebook şi Instagram, s-au confruntat marţi dimineaţa cu defecţiuni tehnice.\n										\n					\n					\n									', '/ro/facebook-si-instagram-nu-au-functionat-in-dimineata-zilei-de-marti-cine-a-revendicat-un-atac-online-asupra-retelelor-de-socializare', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/ZSBRmirxRE4/facebook-si-instagram-nu-au-functionat-in-dimineata-zilei-de-marti-cine-a-revendicat-un-atac-online-asupra-retelelor-de-socializare-13787966', '2015.01.27', 0),
(89, 4, 'gandul.info', 'REDUCERI EMAG. EMAG oferă REDUCERI mari de ''''Revoluţia preţurilor''''', 'REDUCERI EMAG. EMAG lansează o nouă promoţie, numită ''''Revoluţia preţurilor'''', care durează trei zile, 27, 28 şi 29 ianuarie, şi oferă cumpărătorilor REDUCERI şi oferte similare celor de Black Friday, conform EMAG.\n										\n					\n					\n									', '/ro/reduceri-emag-emag-ofera-reduceri-mari-de-revolutia-preturilor', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/7095-OdOomk/reduceri-emag-emag-ofera-reduceri-mari-de-revolutia-preturilor-13787602.html', '2015.01.27', 0),
(90, 4, 'gandul.info', 'REDUCERI ALTEX. ALTEX oferă REDUCERI de până la 70% în această noapte', 'REDUCERI ALTEX. ALTEX organizează azi, 27 ianuarie, Noaptea Devoratorilor de Preţuri, exclusiv pe www.altex.ro. Oferta promoţională este disponibilă după ora 20.00.\n										\n					\n					\n									', '/ro/reduceri-altex-altex-ofera-reduceri-de-pana-la-70-in-aceasta-noapte', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/anMayfhVae0/reduceri-altex-altex-ofera-reduceri-de-pana-la-70-in-aceasta-noapte-13787641.html', '2015.01.27', 0),
(91, 4, 'gandul.info', 'Ce „moştenire” a lăsat statului regretatul Gică Petrescu ', 'Asociaţia de proprietari a blocului în care a locuit regretatul Gică Petrescu a dat în judecată statul român, cerând plata unor restanţe la întreţinere.\n										\n					\n					\n									', '/ro/ce-mostenire-a-lasat-statului-regretatul-gica-petrescu', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Se7elyEOvIE/ce-mostenire-a-lasat-statului-regretatul-gica-petrescu-13784694', '2015.01.27', 0),
(92, 4, 'gandul.info', 'Gestul inedit al unui iubitor de animale', 'Când a aflat că mastiff-ul său englez este pe moarte, tânăra din imagine a decis să transforme ultimele luni de viaţă ale câinelui într-o aventură.\n										\n					\n					\n									', '/ro/gestul-inedit-al-unui-iubitor-de-animale', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/kg-P8Wz2rlQ/gestul-inedit-al-unui-iubitor-de-animale-13785085', '2015.01.27', 0),
(93, 4, 'gandul.info', 'Mai multe medicamente uzuale cresc riscul de a dezvolta o boală gravă', 'Mai multe medicamente care sunt administrate în mod curent cresc riscul de demenţă, inclusiv riscul de dezvoltare a maladiei Alzheimer, la persoanele în vârstă care primesc aceste substanţe în doze mari sau pentru perioade îndelungate, potrivit unui studiu publicat luni în Statele Unite.\n										\n					\n					\n									', '/ro/mai-multe-medicamente-uzuale-cresc-riscul-de-a-dezvolta-o-boala-grava', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/fgZuvUjeToU/mai-multe-medicamente-uzuale-cresc-riscul-de-a-dezvolta-o-boala-grava-13788057', '2015.01.27', 0),
(94, 4, 'gandul.info', 'Cum arată Novoafonskaia, peştera în care există o linie de metrou. GALERIE FOTO', 'Peştera Novoafonskaia din Abhazia dispune de o linie de metrou proprie, scrie englishrussia.com. Acest obiectiv turistic a fost descoperit recent şi a ajuns în atenţia publicului în 1961. În anii ''80, peştera a devenit o destinaţie turistică sovietică foarte populară.\n										\n					\n					\n									', '/ro/cum-arata-novoafonskaia-pestera-in-care-exista-o-linie-de-metrou-galerie-foto', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/5Kr6Zh35HzQ/cum-arata-novoafonskaia-pestera-in-care-exista-o-linie-de-metrou-galerie-foto-13787560', '2015.01.27', 0),
(95, 4, 'gandul.info', 'Această tânără se luptă azi pentru un titlu de Miss. De ce era însă batjocorită la şcoală', 'O tânără din Marea Britanie a reuşit le dea o lecţie foştilor colegi de şcoală o batjocoreau. Rebekah Hemsley a devenit model.\n										\n					\n					\n									', '/ro/aceasta-tanara-se-lupta-azi-pentru-un-titlu-de-miss-de-ce-era-insa-batjocorita-la-scoala', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/jUw1noceMvo/aceasta-tanara-se-lupta-azi-pentru-un-titlu-de-miss-de-ce-era-insa-batjocorita-la-scoala-13787845', '2015.01.27', 0),
(96, 4, 'gandul.info', 'Tarom va lansa o nouă cursă', 'Compania aeriană Tarom va opera curse directe pe ruta Bucureşti - Valencia - Bucureşti, în perioada 19 iunie - 28 septembrie, biletele fiind puse deja în vânzare.\n										\n					\n					\n									', '/ro/tarom-va-lansa-o-noua-cursa', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/PKOupOlnvAM/tarom-va-lansa-o-noua-cursa-13787645', '2015.01.27', 0),
(97, 4, 'gandul.info', 'Un fotbalist senegalez a murit la 26 de ani', 'Mijlocaşul senegalez al echipei luxemburgheze F91 Dudelange Oumar Sylla a decedat, luni, la vârsta de 26 de ani, în urma unui cancer la ficat, informează site-ul oficial al UEFA.\n										\n					\n					\n									', '/ro/un-fotbalist-senegalez-a-murit-la-26-de-ani', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/jkwbvgiSXBI/un-fotbalist-senegalez-a-murit-la-26-de-ani-13787678', '2015.01.27', 0),
(98, 4, 'gandul.info', 'Tecău şi Mergea se vor întâlni în noaptea de marţi spre miercuri', 'Românii Horia Tecău şi Florin Mergea vor fi adversari în sferturile de finală ale probei de dublu masculin de la Australian Open, meciul fiind programat pe terenul doi, în noaptea de marţi spre miercuri, informează site-ul oficial al competiţiei.\n										\n					\n					\n									', '/ro/tecau-si-mergea-se-vor-intalni-in-noaptea-de-marti-spre-miercuri', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/a0GqSm3pkBs/tecau-si-mergea-se-vor-intalni-in-noaptea-de-marti-spre-miercuri-13787749', '2015.01.27', 0),
(99, 4, 'gandul.info', 'Maria Şarapova s-a calificat în semifinalele Australian Open', 'Jucătoarea rusă de tenis Maria Şarapova, locul 2 WTA, a învins-o, marţi, cu scorul de 6-3, 6-2, pe sportiva canadiană Eugenie Bouuchard, locul 7 WTA, şi s-a calificat în semifinalele turneului Australian Open.\n										\n					\n					\n									', '/ro/maria-sarapova-sa-calificat-in-semifinalele-australian-open', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/XE--rALKH2A/maria-sarapova-s-a-calificat-in-semifinalele-australian-open-13787493', '2015.01.27', 0),
(100, 4, 'gandul.info', 'Justiţia din Turcia ordonă Facebook să interzică anumite pagini, altfel va interzice accesul cetăţenilor săi la reţeaua de socializare', 'Justiţia turcă a ordonat Facebook să interzică paginile al căror conţinut constituie o "insultă" la adresa imaginii Profetului Mahomed şi a ameninţat că va interzice accesul la reţeaua de socializare în Turcia dacă aceasta nu se va supune, a anunţat presa turcă, citată de AFP.\n										\n					\n					\n									', '/ro/justitia-din-turcia-ordona-facebook-sa-interzica-anumite-pagini-altfel-va-interzice-accesul-cetatenilor-sai-la-reteaua-de-socializare', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Ae1ugjpms_Q/justitia-din-turcia-ordona-facebook-sa-interzica-anumite-pagini-altfel-va-interzice-accesul-cetatenilor-sai-la-reteaua-de-socializare-13788005', '2015.01.27', 0),
(101, 4, 'gandul.info', 'Prima reacţie a rusoaicei care a bătut-o pe Halep: A fost foarte greu, dar şi Halep a făcut ceva greşeli', 'Rusoaica Ekaterina Makarova, locul 11 WTA şi cap de serie numărul 10, care a învins-o pe Simona Halep, locul 3 WTA, în sferturile de finală ale Australian Open, primul turneu de Grand Slam al anului, a declarat că nu s-a gândit la scor în timpul meciului, subliniind că românca a făcut greşeli.\n										\n					\n					\n									', '/ro/prima-reactie-a-rusoaicei-care-a-batuto-pe-halep-a-fost-foarte-greu-dar-si-halep-a-facut-ceva-greseli', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/glpCinFRvGk/prima-reactie-a-rusoaicei-care-a-batut-o-pe-halep-a-fost-foarte-greu-dar-si-halep-a-facut-ceva-greseli-13787475', '2015.01.27', 0);
INSERT INTO `news` (`id`, `country_id`, `author`, `title`, `description`, `site_link`, `link`, `pubdate`, `views`) VALUES
(102, 4, 'gandul.info', 'Ninsoarea transformă New York-ul într-un oraş fantomă - GALERIE FOTO', 'New York, oraşul care nu doarme niciodată, se pregătea luni seara de o noapte calmă din cauza unei furtuni de zăpadă, în timp ce autorităţile au mobilizat mijloace importante, iar podurile şi tunelurile au fost închise, transportul în comun a fost oprit, iar circulaţia interzisă, relatează AFP. \n										\n					\n					\n									', '/ro/ninsoarea-transforma-new-yorkul-intrun-oras-fantoma-galerie-foto', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/JK-huD-tfhY/ninsoarea-transforma-new-york-ul-intr-un-oras-fantoma-galerie-foto-13787526', '2015.01.27', 0),
(103, 4, 'gandul.info', 'Un sicriu cu iniţialele lui Miguel de Cervantes, descoperit de cei care îi caută mormântul', 'Istoricii aflaţi în căutarea mormântului unuia dintre cei mai mai renumiţi scriitori spanioli, Miguel de Cervantes, au anunţat, luni, că au descoperit sub capela unei biserici din Madrid fragmente dintr-un sicriu pe care sunt gravate iniţialele romancierului, informează Reuters.\n										\n					\n					\n									', '/ro/un-sicriu-cu-initialele-lui-miguel-de-cervantes-descoperit-de-cei-care-ii-cauta-mormantul', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/XYKPaLdMHfQ/un-sicriu-cu-initialele-lui-miguel-de-cervantes-descoperit-de-cei-care-ii-cauta-mormantul-13787945', '2015.01.27', 0),
(104, 4, 'gandul.info', 'Site Australian Open: Makarova a "demolat-o" pe Halep în 69 de minute', 'Site-ul oficial al turneului Australian Open a notat că Ekaterina Makarova, locul 10 WTA, a "demolat-o" pe Simona Halep, favorită 3, marţi, în sferturile de finală, subliniind că rusoaica a cedat doar patru ghemuri.\n										\n					\n					\n									', '/ro/site-australian-open-makarova-a-demolato-pe-halep-in-69-de-minute', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/dX6gf47GPv8/site-australian-open-makarova-a-demolat-o-pe-halep-in-69-de-minute-13787477', '2015.01.27', 0),
(105, 4, 'gandul.info', 'Fostul internaţional Faustino Asprilla a fost şantajat şi ameninţat, până a părăsit Columbia. După câteva luni, a primit o veste bună', 'Poliţia columbiană a arestat, luni, o persoană pentru presupuse ameninţări şi şantaj la adresa fostului internaţional Faustino Asprilla, informează AFP.\n										\n					\n					\n									', '/ro/fostul-international-faustino-asprilla-a-fost-santajat-si-amenintat-pana-a-parasit-columbia-dupa-cateva-luni-a-primit-o-veste-buna', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/LHeb1ugwb7k/fostul-international-faustino-asprilla-a-fost-santajat-si-amenintat-pana-a-parasit-columbia-dupa-cateva-luni-a-primit-o-veste-buna-13787861', '2015.01.27', 0),
(106, 4, 'gandul.info', 'Rafael Nadal a fost învins de Tomas Berdych în sferturi de finală la Australian Open', 'Tenismanul spaniol Rafael Nadal, cap de serie numărul 3, a fost învins, marţi, cu scorul de 6-2, 6-0, 7-6 (5), de cehul Tomas Berdych, al şaptelea favorit al competiţiei, în sferturi de finală la Australian Open, primul turneu de Grand Slam al anului, informează AFP.\n										\n					\n					\n									', '/ro/rafael-nadal-a-fost-invins-de-tomas-berdych-in-sferturi-de-finala-la-australian-open', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/i3HI4FlIPPI/rafael-nadal-a-fost-invins-de-tomas-berdych-in-sferturi-de-finala-la-australian-open-13787617', '2015.01.27', 0),
(107, 4, 'gandul.info', 'Florin Mergea, eliminat în optimi de finală la dublu mixt, la Australian Open', 'Perechea Florin Mergea/Michaella Krajicek (România/Olanda) a ratat, marţi, calificarea în sferturile de finală ale probei de dublu mixt de la Australian Open, primul turneu de Grand Slam al anului, informează site-ul oficial al competiţiei.\n										\n					\n					\n									', '/ro/florin-mergea-eliminat-in-optimi-de-finala-la-dublu-mixt-la-australian-open', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/-LNkLyN0174/florin-mergea-eliminat-in-optimi-de-finala-la-dublu-mixt-la-australian-open-13787550', '2015.01.27', 0),
(108, 4, 'gandul.info', 'Încep filmările pentru "Piraţii din Caraibe 5". Cine joacă rolul feminin principal', 'Filmările pentru cel de-al cincilea lungmetraj din seria "Piraţii din Caraibe/ Pirates Of The Caribbean", "Dead Men Tell No Tales", vor debuta în luna februarie, în Queensland, Australia, rolul principal feminin fiind interpretat de actriţa Kaya Scodelario, informează dailymail.co.uk.\n										\n					\n					\n									', '/ro/incep-filmarile-pentru-piratii-din-caraibe-5-cine-joaca-rolul-feminin-principal', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/jF2g39xKOCc/incep-filmarile-pentru-piratii-din-caraibe-5-cine-joaca-rolul-feminin-principal-13787622', '2015.01.27', 0),
(109, 4, 'gandul.info', 'Fost oficial al CIA, declarat vinovat pentru că a furnizat informaţii secrete unui jurnalist', 'Un fost oficial din cadrul CIA a fost declarat vinovat, luni, în Alexandria (Virginia, est) pentru că a furnizat informaţii secrete privind dosarul nuclear iranian unui jurnalist de la New York Times, a anunţat Departamentul Justiţiei, citat de AFP.\n										\n					\n					\n									', '/ro/fost-oficial-al-cia-declarat-vinovat-pentru-ca-a-furnizat-informatii-secrete-unui-jurnalist', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/2a3pz_CSnzI/fost-oficial-al-cia-declarat-vinovat-pentru-ca-a-furnizat-informatii-secrete-unui-jurnalist-13787605', '2015.01.27', 0),
(110, 4, 'realitatea.net', 'De ce au căzut Facebook si Instagram! Răspunsul Facebook', 'Rețeaua de socializare Facebook, a cărei funcționare a fost perturbată timp de 50 de minute marți dimineață, &icirc;n &icirc;ntreaga lume, a negat că a fost ținta unui atac al hackerilor, așa cum susțineau zvonuri apărute anterior pe internet, relatează AFP, ', '/ro/de-ce-au-cazut-facebook-si-instagram-raspunsul-facebook', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1bfb/l/0L0Srealitatea0Bnet0Cde0Ece0Eau0Ecazut0Efacebook0Esi0Einstagram0Eraspunsul0Efacebook0I16186680Bhtml/story01.htm', '2015.01.27', 0),
(111, 4, 'realitatea.net', 'Raport european: Supravegherea în masă ameninţă drepturile omului şi este contraproductivă', 'Un raport al Comisiei Juridice a Adunării Parlamentare a Consiliului Europei (APCE) afirmă că practica supravegherii &icirc;n masă, de tipul celei dezvăluite de Edward Snowden, ameninţă drepturile fundamentale ale omului şi este contraproductivă. ', '/ro/raport-european-supravegherea-in-masa-ameninta-drepturile-omului-si-este-contraproductiva', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c05/l/0L0Srealitatea0Bnet0Craport0Eeuropean0Esupravegherea0Ein0Emasa0Eameninta0Edrepturile0Eomului0Esi0Eeste0Econtraproductiva0I16186670Bhtml/story01.htm', '2015.01.27', 0),
(112, 4, 'realitatea.net', 'BREAKING NEWS: George Maior și-a dat demisia din fruntea SRI', 'George Maior și-a dat demisia din funcția de director al Serviciului Rom&acirc;n de Informații. ', '/ro/breaking-news-george-maior-sia-dat-demisia-din-fruntea-sri', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c0c/l/0L0Srealitatea0Bnet0Cgeorge0Emaior0Ei0Ea0Edat0Edemisia0Ede0Ela0Esri0I16186660Bhtml/story01.htm', '2015.01.27', 0),
(113, 4, 'realitatea.net', 'De ce Nutella din Germania are alt gust decât cea din România', 'Cei care se pl&acirc;ng de faptul că ciocolata din borcanele Nutella cumpărate din Rom&acirc;nia, are alt gust (nu at&acirc;t de bun) precum cea din borcanele achiziţionate din Germania, de exemplu, nu sunt departe de adevăr. ', '/ro/de-ce-nutella-din-germania-are-alt-gust-decat-cea-din-romania', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c14/l/0L0Srealitatea0Bnet0Cde0Ece0Enutella0Edin0Egermania0Eare0Ealt0Egust0Edecat0Ecea0Edin0Eromania0I16186610Bhtml/story01.htm', '2015.01.27', 0),
(114, 4, 'realitatea.net', 'CURS BNR. Anunț surprinzător de la BNR tocmai în timpul vizitei FMI', 'CURS BNR. Francul elveţian s-a depreciat marți, 27 ianuarie. semnificativ &icirc;n raport cu leul, pentru a doua zi consecutiv. ', '/ro/curs-bnr-anunt-surprinzator-de-la-bnr-tocmai-in-timpul-vizitei-fmi', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c1c/l/0L0Srealitatea0Bnet0Ccurs0Ebnr0Efrancul0Eeuro0Edolarul0I16186480Bhtml/story01.htm', '2015.01.27', 0),
(115, 4, 'realitatea.net', 'Cele mai bune SUV-uri second hand pe care le poţi cumpăra din Germania', 'Raportul T&Uuml;V pentru 2015 ne pune &icirc;n faţă cele mai fiabile maşini second hand din Germania, dar şi cele mai puţin fiabile. ', '/ro/cele-mai-bune-suvuri-second-hand-pe-care-le-poti-cumpara-din-germania', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c25/l/0L0Srealitatea0Bnet0Ccele0Emai0Ebune0Esuv0Euri0Esecond0Ehand0Epe0Ecare0Ele0Epoti0Ecumpara0Edin0Egermania0I16186570Bhtml/story01.htm', '2015.01.27', 0),
(116, 4, 'realitatea.net', 'Profeția GROAZNICĂ făcută de un preot din România: Copilul DIAVOLULUI are 15 ani! Ce urmează', 'La un moment-dat, părintele Cleopa Jurj avertizeaza că o mare nenorocire se va abate asupra omenirii prin anul 2032. ', '/ro/profetia-groaznica-facuta-de-un-preot-din-romania-copilul-diavolului-are-15-ani-ce-urmeaza', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c2e/l/0L0Srealitatea0Bnet0Cprofe0Eia0Egroaznica0Efacuta0Ede0Eun0Epreot0Edin0Eromania0Ecopilul0Ediavolului0Eare0E150Eani0Ece0Eurmeaza0I16186460Bhtml/story01.htm', '2015.01.27', 0),
(117, 4, 'realitatea.net', 'Trei răniţi într-un accident în care a fost implicat un autobuz al regiei locale de transport Braşov', 'Trei persoane au fost rănite, marţi, după ce un autoturism ajuns pe contrasens s-a ciocnit cu un autobuz al regiei de transport &icirc;n comun din Braşov, iar &icirc;n urma impactului autobuzul a ajuns pe trotuar, a lovit un st&acirc;lp de electricitate şi s-a oprit ', '/ro/trei-raniti-intrun-accident-in-care-a-fost-implicat-un-autobuz-al-regiei-locale-de-transport-brasov', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c35/l/0L0Srealitatea0Bnet0Ctrei0Eraniti0Eintr0Eun0Eaccident0Ein0Ecare0Ea0Efost0Eimplicat0Eun0Eautobuz0Eal0Eregiei0Elocale0Ede0Etransport0Ebrasov0I16186420Bhtml/story01.htm', '2015.01.27', 0),
(118, 4, 'realitatea.net', 'Samsung Z1, telefonul ieftin şi bun care SCRIE ISTORIE', 'Sud-coreenii de la Samsung au &icirc;nregistrat un succes fulminant cu primul lor telefon care rulează sistemul de operare TIZEN. Modelul Samsung Z1 a fost lansat &icirc;n premieră pe piaţa indiană la preţul de numai 92 de dolari, relatează GadgetReport.ro ', '/ro/samsung-z1-telefonul-ieftin-si-bun-care-scrie-istorie', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c3f/l/0L0Srealitatea0Bnet0Csamsung0Ez10Etelefonul0Eieftin0Esi0Ebun0Ecare0Escrie0Eistorie0I16186470Bhtml/story01.htm', '2015.01.27', 0),
(119, 4, 'realitatea.net', 'BNR: Șase bănci sunt de acord cu conversia creditelor din franci în lei', 'Viceguvernatorul BNR, Bogdan Olteanu, a declarat, luni seara, că şase bănci din Rom&acirc;nia au fost de acord cu conversia creditelor din franci elveţieni &icirc;n lei. ', '/ro/bnr-sase-banci-sunt-de-acord-cu-conversia-creditelor-din-franci-in-lei', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c43/l/0L0Srealitatea0Bnet0Cbnr0Ease0Ebanci0Esunt0Ede0Eacord0Ecu0Econversia0Ecreditelor0Ein0Elei0I16186330Bhtml/story01.htm', '2015.01.27', 0),
(120, 4, 'realitatea.net', 'Avertismentul ORIBIL al unui preot: COLA conține SÂNGELE copiilor', 'Părintele Cleopa Garj de la mănăstirea arădeană Gai a luat &icirc;n vizor şi băuturile răcoritoare pe bază de cola. ', '/ro/avertismentul-oribil-al-unui-preot-cola-contine-sangele-copiilor', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c49/l/0L0Srealitatea0Bnet0Cavertismentul0Eoribil0Eal0Eunui0Epreot0Ecola0Econ0Eine0Esangele0Ecopiilor0I16186350Bhtml/story01.htm', '2015.01.27', 0),
(121, 4, 'realitatea.net', 'Zina Dumitrescu, apariţie inedită: a părăsit azilul pentru a participa la aniversarea unei vedete', 'Dana Savuica si-a sarbatorit zilele trecute ziua de nastere, dand o petrecere de zile mari. La eveniment a luat parte si Zina Dumitrescu, care a iesit din azil special pentru aceasta ocazie. ', '/ro/zina-dumitrescu-aparitie-inedita-a-parasit-azilul-pentru-a-participa-la-aniversarea-unei-vedete', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf1c50/l/0L0Srealitatea0Bnet0Czina0Edumitrescu0Eaparitie0Einedita0Ea0Eparasit0Eazilul0Epentru0Ea0Eparticipa0Ela0Eaniversarea0Eunei0Evedete0I16186260Bhtml/story01.htm', '2015.01.27', 0),
(122, 4, 'realitatea.net', 'SURPRIZĂ - Ce a spus Cristian Tudor Popescu despre EŞECUL Simonei Halep. I-a UIMIT pe toţi', 'Editorialistul G&acirc;ndul, Cristian Tudor Popescu, a scris o opinie despre eliminarea Simonei Halep de la Australian Open. ', '/ro/surpriza-ce-a-spus-cristian-tudor-popescu-despre-esecul-simonei-halep-ia-uimit-pe-toti', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf490e/l/0L0Srealitatea0Bnet0Csurpriza0Ece0Ea0Espus0Ecristian0Etudor0Epopescu0Edespre0Eesecul0Esimonei0Ehalep0Ei0Ea0Euimit0Epe0Etoti0I16186290Bhtml/story01.htm', '2015.01.27', 0),
(123, 4, 'realitatea.net', 'Reacţia ORIGINALĂ a lui Cătălin Tolontan după ce Simona Halep a părăsit Australian Open', 'Redactorul-şef GSP. Cătălin Tolontan, a avut o intervenţie telefonică la radio Europa FM, unde a vorbit despre eliminarea Simonei Halep de la Australian Open. ', '/ro/reactia-originala-a-lui-catalin-tolontan-dupa-ce-simona-halep-a-parasit-australian-open', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf4918/l/0L0Srealitatea0Bnet0Creactia0Eoriginala0Ea0Elui0Ecatalin0Etolontan0Edupa0Ece0Esimona0Ehalep0Ea0Eparasit0Eaustralian0Eopen0I16186240Bhtml/story01.htm', '2015.01.27', 0),
(124, 4, 'realitatea.net', 'Un pui de jaguar, adoptat de o cățelușă, la o grădină zoo din România', 'Un pui de jaguar de patru luni e noua senzaţie de la Zoo Sibiu. Adoptat de o căţeluşă, care l-a hrănit cu lapte timp de o lună, Mihai, căci aşa a fost botezat de &icirc;ngrijitorii de la Zoo Sibiu, &icirc;ncepe abia acum să intre &icirc;n contact cu oamenii şi ', '/ro/un-pui-de-jaguar-adoptat-de-o-catelusa-la-o-gradina-zoo-din-romania', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf4924/l/0L0Srealitatea0Bnet0Cun0Epui0Ede0Ejaguar0Eadoptat0Ede0Eo0Eca0Eelu0Ea0Ela0Eo0Egradina0Ezoo0Edin0Eromania0I161860A30Bhtml/story01.htm', '2015.01.27', 0),
(125, 4, 'realitatea.net', 'Apartamentele vechi, mai scumpe decât cele noi în București, dar mai ieftine în provincie', 'Bucureștenii continuă să pună mare preț pe apropierea de centrul orașului, &icirc;n timp ce locuitorii din provincie sunt mai atrași de locuințele noi, ceea ce face ca apartamentele construite &icirc;n Capitală &icirc;n perioada 1978 - 2000 să fie mai scumpe ', '/ro/apartamentele-vechi-mai-scumpe-decat-cele-noi-in-bucuresti-dar-mai-ieftine-in-provincie', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf4931/l/0L0Srealitatea0Bnet0Capartamentele0Evechi0Emai0Escumpe0Edecat0Ecele0Enoi0Ein0Ebucure0Eti0Edar0Emai0Eieftine0Ein0Eprovincie0I16186220Bhtml/story01.htm', '2015.01.27', 0),
(126, 4, 'realitatea.net', 'Avocatul Poporului declanșează o anchetă privind condițiile din închisori', 'Avocatul Poporului s-a sesizat din oficiu şi va desfăşura o anchetă &icirc;n &icirc;ntreg sistemul penitenciar din Rom&acirc;nia. Decizia vine ca urmare a dezvăluirilor făcute de Realitatea TV. ', '/ro/avocatul-poporului-declanseaza-o-ancheta-privind-conditiile-din-inchisori', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf493c/l/0L0Srealitatea0Bnet0Cavocatul0Epoporului0Eancheta0Ein0Epenitenciare0I161860A70Bhtml/story01.htm', '2015.01.27', 0),
(127, 4, 'realitatea.net', 'O bancă, la un pas să fie executată silit', 'O bancă este aproape de executarea silită: trebuie să plătească 30.000 de franci elvețieni unor clienți. Executorii spun că vor trece la acțiune. ', '/ro/o-banca-la-un-pas-sa-fie-executata-silit', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf4944/l/0L0Srealitatea0Bnet0Co0Ebanca0Eeste0Eaproape0Ede0Eexecutarea0Esilita0I161860A20Bhtml/story01.htm', '2015.01.27', 0),
(128, 4, 'realitatea.net', 'Acestea sunt cauzele mai puțin știute ale febrei!', 'O infecție virală sau bacteriană este una dintre cele mai comune cauze ale apariței febrei; creșterea temperaturii corpului este un semn că sistemul imunitar &icirc;ncearcă să lupte cu&nbsp; infecția. ', '/ro/acestea-sunt-cauzele-mai-putin-stiute-ale-febrei', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf4952/l/0L0Srealitatea0Bnet0Cacestea0Esunt0Ecauzele0Emai0Epu0Ein0Etiute0Eale0Efebrei0I161860A10Bhtml/story01.htm', '2015.01.27', 0),
(129, 4, 'realitatea.net', 'Tratament minune pentru OSTEOPOROZĂ cu miere, nucă şi ouă', 'Conform statisticilor Ministerului sanatatii in tara noastra se estimeaza ca aproape 1,5 milioane de romani sufera de osteoporoza, dintre care 88% sunt femei, notează site-ul frunza-verde.ro. ', '/ro/tratament-minune-pentru-osteoporoza-cu-miere-nuca-si-oua', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/42bf4963/l/0L0Srealitatea0Bnet0Ctratament0Eminune0Epentru0Eosteoporoza0Ecu0Emiere0Enuca0Esi0Eoua0I161860A0A0Bhtml/story01.htm', '2015.01.27', 0);

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `rss`
--

CREATE TABLE IF NOT EXISTS `rss` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_id` int(11) NOT NULL,
  `link` varchar(255) CHARACTER SET utf8 NOT NULL,
  `active` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Salvarea datelor din tabel `rss`
--

INSERT INTO `rss` (`id`, `country_id`, `link`, `active`) VALUES
(1, 3, 'http://rss.cnn.com/rss/edition.rss', 1),
(2, 3, 'http://www.yelp.com/syndicate/area/rss.xml?loc=New+York%2C+NY', 1),
(3, 4, 'http://feeds.feedburner.com/gandul/Mjcu', 1),
(4, 4, 'http://realitatea.feedsportal.com/c/32533/fe.ed/rss.realitatea.net/stiri.xml', 1);

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `slugs`
--

CREATE TABLE IF NOT EXISTS `slugs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country` varchar(255) CHARACTER SET utf8 NOT NULL,
  `slug` varchar(255) CHARACTER SET utf8 NOT NULL,
  `country2` varchar(255) CHARACTER SET utf8 NOT NULL,
  `language` varchar(255) CHARACTER SET utf8 NOT NULL,
  `timezone` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Salvarea datelor din tabel `slugs`
--

INSERT INTO `slugs` (`id`, `country`, `slug`, `country2`, `language`, `timezone`) VALUES
(3, 'United States', 'us', 'United States', 'us', 1),
(4, 'Romania', 'ro', 'România', 'ro', 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
