-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Gazda: 127.0.0.1
-- Timp de generare: 23 Sep 2014 la 13:53
-- Versiune server: 5.5.27
-- Versiune PHP: 5.4.7

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Baza de date: `news`
--

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `news`
--

CREATE TABLE IF NOT EXISTS `news` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_id` int(11) NOT NULL,
  `author` varchar(255) CHARACTER SET utf8 NOT NULL,
  `title` varchar(255) CHARACTER SET utf16 NOT NULL,
  `description` varchar(1000) CHARACTER SET utf8 NOT NULL,
  `link` varchar(255) CHARACTER SET utf8 NOT NULL,
  `pubdate` varchar(255) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=104 ;

--
-- Salvarea datelor din tabel `news`
--

INSERT INTO `news` (`id`, `country_id`, `author`, `title`, `description`, `link`, `pubdate`) VALUES
(1, 2, 'CNN.com - Top Stories', 'We''re at tipping point on climate', 'We might be at a tipping point in the global battle against climate change, writes Ford Foundation President Darren Walker.', 'http://edition.cnn.com/2014/09/22/opinion/walker-climate-tipping-point/index.html?eref=edition', 'Tue, 23 Sep 2014 00:55:40 EDT'),
(2, 2, 'CNN.com - Top Stories', 'Revealed: How ''Islamic State'' is run', 'Put yourself in the shoes (and seventh-century black robes) of ISIS'' Abu Bakr al-Baghdadi, the mysterious boss of the terror group that is striking fear into the hearts of leaders around the world. ', 'http://edition.cnn.com/2014/09/18/world/meast/isis-syria-iraq-hierarchy/index.html?eref=edition', 'Tue, 23 Sep 2014 05:06:27 EDT'),
(3, 2, 'CNN.com - Top Stories', 'Hypocrisy of sports gambling foes', 'As a society, it seems we''ll always struggle with our vices. Our governments are less morally conflicted, it seems. ', 'http://edition.cnn.com/2014/09/22/opinion/cevallos-let-sports-gambling-flourish/index.html?eref=edition', 'Tue, 23 Sep 2014 05:07:03 EDT'),
(4, 2, 'CNN.com - Top Stories', 'Five Arab nations join attacks', '• At least 20 targets in and around Syrian city of Raqqa hit\n• Five Arab countries involved\n• Bombers, fighter jets, missiles used', 'http://edition.cnn.com/2014/09/23/world/meast/isis-airstrikes/index.html?eref=edition', 'Tue, 23 Sep 2014 06:37:55 EDT'),
(5, 2, 'CNN.com - Top Stories', 'ISIS airstrikes: Key questions', 'The United States and several Arab nations carried out airstrikes against ISIS in Syria early Tuesday, intensifying the campaign against the Islamic militant group.', 'http://edition.cnn.com/2014/09/23/world/meast/syria-isis-airstrikes-explainer/index.html?eref=edition', 'Tue, 23 Sep 2014 05:23:41 EDT'),
(6, 2, 'CNN.com - Top Stories', 'Jordan ''part of the strike''', 'CNN''s Becky Anderson talks to Jordanian Govt. Spokesman Mohammad Al Momani about Jordan''s involvement in ISIS airstrikes.', 'http://edition.cnn.com/video/data/2.0/video/world/2014/09/23/intv-anderson-jordan-involvement.cnn.html?eref=edition', 'Tue, 23 Sep 2014 01:55:49 EDT'),
(7, 2, 'CNN.com - Top Stories', 'Congress reacts to airstrikes', 'As the Pentagon launched a barrage of airstrikes inside Syria late Monday, signaling a new phase in the United States'' involvement in the fight against ISIS, Congress had already left town and most of the reaction from lawmakers came from those who had pressed the administration to act sooner to destroy the terror group.', 'http://edition.cnn.com/2014/09/23/politics/syria-airstrikes-congress-reaction/index.html?eref=edition', 'Tue, 23 Sep 2014 01:41:27 EDT'),
(8, 2, 'CNN.com - Top Stories', 'Russians in ISIS a threat', 'CNN''s Matthew Chance speaks with the director of the Kremlin''s "New Threats" committee about ISIS.', 'http://edition.cnn.com/video/data/2.0/video/world/2014/09/23/pkg-chance-russia-and-isis.cnn.html?eref=edition', 'Tue, 23 Sep 2014 04:45:37 EDT'),
(9, 2, 'CNN.com - Top Stories', 'Ebola kills 2,800 in 6 months - WHO', 'The death toll from Ebola in West Africa has now climbed to more than 2,800, with 5,800 cases confirmed as of Monday, the World Health Organization said.', 'http://edition.cnn.com/2014/09/23/world/africa/ebola-outbreak/index.html?eref=edition', 'Tue, 23 Sep 2014 05:34:57 EDT'),
(10, 2, 'CNN.com - Top Stories', 'Israeli teen murder suspects shot', 'A Palestinian man who Israel says was responsible for the kidnapping and killing of three Israeli teens earlier in the summer was shot and killed by the military. Another suspect was seriously wounded, the military said Tuesday. ', 'http://edition.cnn.com/2014/09/23/world/meast/israel-teen-kidnapping-suspects/index.html?eref=edition', 'Tue, 23 Sep 2014 06:34:41 EDT'),
(11, 2, 'CNN.com - Top Stories', 'China jails Uyghur scholar for life', 'Less than a week after a tightly controlled trial, a Chinese court Tuesday found a prominent Uyghur scholar guilty of "separatism" and sentenced him to life in prison, his lawyer said.', 'http://edition.cnn.com/2014/09/23/world/asia/china-scholar-sentence/index.html?eref=edition', 'Tue, 23 Sep 2014 04:08:02 EDT'),
(12, 2, 'CNN.com - Top Stories', 'China torture trade ''flourishing''', 'The manufacture and export of torture devices by companies in China is flourishing, says the human rights organization in a new report.', 'http://edition.cnn.com/2014/09/22/world/asia/china-amnesty-torture-tools/index.html?eref=edition', 'Tue, 23 Sep 2014 01:22:44 EDT'),
(13, 2, 'CNN.com - Top Stories', 'Climate change focus at UNGA', 'The first item on the long list of issues to be addressed at the United Nations General Assembly in New York this week: Climate change. ', 'http://edition.cnn.com/2014/09/23/politics/obama-un-climate-change/index.html?eref=edition', 'Tue, 23 Sep 2014 04:43:52 EDT'),
(14, 2, 'CNN.com - Top Stories', 'Superbiker: ''Titanium all over my body''', 'In the largely male-dominated world of the motorsport, South African superbike racer Janine Davies is an anomaly.', 'http://edition.cnn.com/2014/09/23/world/africa/life-in-the-fast-lane-janine-davies/index.html?eref=edition', 'Tue, 23 Sep 2014 05:41:10 EDT'),
(15, 2, 'CNN.com - Top Stories', 'India probe trails MAVEN orbiter', 'Just days behind NASA''s Mars orbiter, an Indian mission could follow suit and make history.', 'http://edition.cnn.com/2014/09/23/world/asia/mars-india-orbiter/index.html?eref=edition', 'Tue, 23 Sep 2014 04:20:33 EDT'),
(16, 2, 'CNN.com - Top Stories', 'Chinese wine myths debunked', 'Do the Chinese really like to mix their Bordeaux with Coca-Cola?', 'http://edition.cnn.com/2014/09/22/world/asia/china-wine-myths/index.html?eref=edition', 'Tue, 23 Sep 2014 01:00:48 EDT'),
(17, 2, 'CNN.com - Top Stories', 'Riding the murder mystery express', 'It''s only as I''m inviting my friend to lunch that I realize the prospect might not sound that appetizing.', 'http://edition.cnn.com/2014/09/23/travel/murder-mystery-train/index.html?eref=edition', 'Tue, 23 Sep 2014 05:58:47 EDT'),
(18, 2, 'CNN.com - Top Stories', 'Is China really scared of this HK student?', 'This Hong Kong activist isn''t old enough to drive, but he''s been branded an "extremist."', 'http://edition.cnn.com/2014/09/21/world/asia/hong-kong-joshua-wong-democracy-protest/index.html?eref=edition', 'Tue, 23 Sep 2014 02:36:41 EDT'),
(19, 2, 'CNN.com - Top Stories', 'Ultimate diving: DON''T try this at home', 'In the world of diving, this is as good as it gets.', 'http://edition.cnn.com/2014/09/22/sport/red-bull-diving-bilbao/index.html?eref=edition', 'Tue, 23 Sep 2014 05:32:27 EDT'),
(20, 2, 'CNN.com - Top Stories', 'The world''s best nightlife cities', 'Which city has the best parties? A "connoisseur" names his top 10.', 'http://edition.cnn.com/2014/09/22/travel/best-nightlife-cities/index.html?eref=edition', 'Tue, 23 Sep 2014 04:54:47 EDT'),
(21, 2, 'CNN.com - Top Stories', 'Face to face with Japan''s tennis ace', 'After his remarkable journey to the U.S. Open final, Japan''s new hero chats with CNN.', 'http://edition.cnn.com/2014/09/22/sport/tennis/tennis-kei-nishikori-q-and-a/index.html?eref=edition', 'Tue, 23 Sep 2014 06:04:47 EDT'),
(22, 2, 'CNN.com - Top Stories', 'Inflight meals ''enjoyed'' at home?', 'Strange though it might seem, there are people who love inflight meals.', 'http://edition.cnn.com/2014/09/22/travel/inflight-food-deliveries/index.html?eref=edition', 'Tue, 23 Sep 2014 01:52:02 EDT'),
(23, 2, 'CNN.com - Top Stories', 'Derek Jeter: A career in pinstripes', 'Photos: Derek Jeter''s life, career', 'http://edition.cnn.com/2014/09/22/worldsport/gallery/derek-jeter/index.html?eref=edition', 'Tue, 23 Sep 2014 00:38:00 EDT'),
(24, 2, 'CNN.com - Top Stories', 'U.S.-led airstrikes: Who''s in, who''s not', 'The campaign of airstrikes against ISIS in Syria has pitted several Arab countries into action alongside the United States. Here''s the lowdown on who''s taking part and who''s missing from the list.', 'http://edition.cnn.com/2014/09/23/world/meast/syria-airstrikes-countries-involved/index.html?eref=edition', 'Tue, 23 Sep 2014 05:52:10 EDT'),
(25, 2, 'CNN.com - Top Stories', 'Twitter user breaks news of airstrikes', 'If anyone doubted Twitter''s power to lead the news, Tuesday''s raids by U.S. forces in Syria offered a new lesson.', 'http://edition.cnn.com/2014/09/23/tech/isis-attack-tweet/index.html?eref=edition', 'Tue, 23 Sep 2014 05:49:59 EDT'),
(26, 2, 'CNN.com - Top Stories', 'What you need to know about campaign', 'The United States and several Arab nations carried out airstrikes against ISIS in Syria early Tuesday, intensifying the campaign against the Islamic militant group.', 'http://edition.cnn.com/2014/09/23/world/meast/syria-isis-airstrikes-explainer/index.html?eref=edition', 'Tue, 23 Sep 2014 05:45:40 EDT'),
(27, 2, 'CNN.com - Top Stories', 'Al Qaeda in Syria: Attack the West', 'Al Qaeda''s new Syrian branch, Khorasan, is seeking new ways to attack America and Europe, with a top U.S. intelligence official saying it has "aspirations for attacks on the homeland."', 'http://edition.cnn.com/2014/09/22/world/meast/al-qaeda-syria-khorasan/index.html?eref=edition', 'Tue, 23 Sep 2014 04:34:26 EDT'),
(28, 2, 'CNN.com - Top Stories', 'Al Qaeda''s new Syrian franchise', 'Intel officials say Khorasan''s mission is to find new ways to attack U.S. and Europe.', 'http://edition.cnn.com/2014/09/22/world/meast/al-qaeda-syria-khorasan/index.html?eref=edition', 'Tue, 23 Sep 2014 04:39:32 EDT'),
(29, 2, 'Recent Reviews Near New York, NY', 'Cee H.''s Review of Yelp Event: Olive Garden - Paramus (5/5) on Yelp', 'YoSteph...what can I say.... You did it again!! Thank you for putting together another great event. Where do I begin ... so we had an 11 course, never-ending tasting menu and I have to say that I was…', 'http://www.yelp.com/biz/yelp-event-olive-garden-paramus?hrid=LOv6jPdeFOjBOvEq51W5fA', 'Tue, 23 Sep 2014 03:07:20  PST'),
(30, 2, 'Recent Reviews Near New York, NY', 'Hyaemee K.''s Review of Pho Bang - Elmhurst (1/5) on Yelp', 'The vietnamese food here is great but the service and the employers are extremely rude and unprofessional. I live a couple of blocks away from this restaurant, so whenever I want a nice refreshing Pho…', 'http://www.yelp.com/biz/pho-bang-elmhurst?hrid=_5mCq4weYlbED1_b_chOdg', 'Tue, 23 Sep 2014 03:04:29  PST'),
(31, 2, 'Recent Reviews Near New York, NY', 'Marc S.''s Review of Two Boots East Village - New York (4/5) on Yelp', 'Not your traditional pie/slice but unique and delicious. For some, it is a bit of an acquired taste with the spicy sauce and sandy crust. When I''m in the mood for it, though, nothing else will do. Go…', 'http://www.yelp.com/biz/two-boots-east-village-new-york?hrid=7orKeNJi5VlpLGixn9Nhsg', 'Tue, 23 Sep 2014 03:03:49  PST'),
(32, 2, 'Recent Reviews Near New York, NY', 'Marc S.''s Review of Tribeca Soho Animal Hospital - New York (5/5) on Yelp', 'Great doctors, although we''re sorry our original left about a year back. Fantastic and friendly staff. Additionally, the fact that they have an office in the West Village that has vet techs on staff…', 'http://www.yelp.com/biz/tribeca-soho-animal-hospital-new-york?hrid=YB9d_xi38PjipQ5KGH57Qg', 'Tue, 23 Sep 2014 03:01:33  PST'),
(33, 2, 'Recent Reviews Near New York, NY', 'Claire S.''s Review of TAO Downtown - New York (5/5) on Yelp', 'Between Evernote, and Yelp.... \nI can find basically everything I''ve ever done anywhere I''ve done it lol :)\n\nThis place is outstanding. \nThe best dinner I believe I''ve ever had. \n\nService was…', 'http://www.yelp.com/biz/tao-downtown-new-york-2?hrid=7YKO_xiaf0QWrjOw7JYCWA', 'Tue, 23 Sep 2014 02:57:43  PST'),
(34, 2, 'Recent Reviews Near New York, NY', 'Marc S.''s Review of Petopia - New York (5/5) on Yelp', 'Great selection of food. Friendly staff. Free Delivery!!!', 'http://www.yelp.com/biz/petopia-new-york?hrid=0kqDqK7ggr3abYBfI-R5ZQ', 'Tue, 23 Sep 2014 02:57:18  PST'),
(35, 2, 'Recent Reviews Near New York, NY', 'Jessica O.''s Review of City of Saints Coffee Roasters - New York (2/5) on Yelp', 'I just happened upon this place and decided to pop in for a cup of joe. $2.25 for a 16 oz. I don''t like my coffee too strong and that was what it was here. I found it strong to the point where I…', 'http://www.yelp.com/biz/city-of-saints-coffee-roasters-new-york?hrid=joHwfGhYHwLQhCltEF50oQ', 'Tue, 23 Sep 2014 02:55:52  PST'),
(36, 2, 'Recent Reviews Near New York, NY', 'Marc S.''s Review of Sarge''s Deli - New York (5/5) on Yelp', 'Of all of the famed delis in NYC, this one gets the least shine. It''s also the best.', 'http://www.yelp.com/biz/sarges-deli-new-york?hrid=jfYoAB1W7aSbhKjm_qPDAQ', 'Tue, 23 Sep 2014 02:55:35  PST'),
(37, 2, 'Recent Reviews Near New York, NY', 'Camille G.''s Review of The Perfect Pint - New York (3/5) on Yelp', 'Went there a couple times, close to work and cool for farewell parties. It''s rather cheap, you can watch TV, sit down and chill. It''s really a no bull-crap place and it''s good to know there is a bar…', 'http://www.yelp.com/biz/the-perfect-pint-new-york?hrid=TXo00YHg5lO5XqF9-lny9g', 'Tue, 23 Sep 2014 02:48:05  PST'),
(38, 2, 'Recent Reviews Near New York, NY', 'Jo L.''s Review of Dramatics Nyc - New York (1/5) on Yelp', 'I went to Dramatics for a trim of my shoulder length hair. The stylist said she understood. Suddenly and without warning, she ran her scissors down my hair  from above my ear. I let out a horrified…', 'http://www.yelp.com/biz/dramatics-nyc-new-york-8?hrid=fbNRVwQoTnEx3ylCGSs9ug', 'Tue, 23 Sep 2014 02:43:38  PST'),
(39, 2, 'Recent Reviews Near New York, NY', 'Billy B.''s Review of UR CUP - New York (3/5) on Yelp', 'tasty coffee, but nothing spectacular, good vibe goin on\nkind of similar to cafes back home in England UK', 'http://www.yelp.com/biz/ur-cup-new-york?hrid=vgluQ5KIodr8J6CJUYJQ0g', 'Tue, 23 Sep 2014 02:40:29  PST'),
(40, 2, 'Recent Reviews Near New York, NY', 'Harold S.''s Review of ABC Kitchen - New York (5/5) on Yelp', 'First stop with friends for a birthday dinner in my honor. We arrived 40 minutes after our reservation and were seated immediately. The wait staff provided incredible service and was very…', 'http://www.yelp.com/biz/abc-kitchen-new-york?hrid=NXn1FRbANMCJ_Z1_wN8tYg', 'Tue, 23 Sep 2014 02:36:35  PST'),
(41, 2, 'Recent Reviews Near New York, NY', 'Camille G.''s Review of Brass Monkey - New York (3/5) on Yelp', 'It''s probably worth more like 3,5 stars.\nHad a great time there celebrating a friend''s birthday. I enjoyed myself also partly due to the fact that I found a starry balloon wandering the ceiling. Sad I…', 'http://www.yelp.com/biz/brass-monkey-new-york?hrid=49DGkCee5cMw3JblNmMyuQ', 'Tue, 23 Sep 2014 02:34:40  PST'),
(42, 2, 'Recent Reviews Near New York, NY', 'Harold S.''s Review of Pio Pio - New York (5/5) on Yelp', 'I had been to their express location in the Upper East Side, so I thought I would give this place a try for a pre theater dinner. I had Lomo Saltado - it was fantastic. Tender steak, delicious…', 'http://www.yelp.com/biz/pio-pio-new-york-7?hrid=1ilqxxOHSKqQKiT7mwnbVA', 'Tue, 23 Sep 2014 02:33:41  PST'),
(43, 2, 'Recent Reviews Near New York, NY', 'Harold S.''s Review of Buddakan - New York (4/5) on Yelp', 'Enjoyed some fine and creative dishes which had great flavors with above average complexity. The decor is very chic and the space well thought out with the exception of the pervasive din of noise…', 'http://www.yelp.com/biz/buddakan-new-york?hrid=xpcJe-R9OTe1_1ptYCn9lQ', 'Tue, 23 Sep 2014 02:31:24  PST'),
(44, 2, 'Recent Reviews Near New York, NY', 'Camille G.''s Review of BentOn Cafe - New York (5/5) on Yelp', 'This place is amazing. For real.\nThe staff is truly Japanese and super kind and polite, and the food too is real Japanese food. It''s cheap, it''s fresh.\nI have tried a lot of their stuff, for lunch or…', 'http://www.yelp.com/biz/benton-cafe-new-york?hrid=a5pyVDjy7HP6JUYMeQPyJQ', 'Tue, 23 Sep 2014 02:24:14  PST'),
(45, 2, 'Recent Reviews Near New York, NY', 'London C.''s Review of Traif - Brooklyn (5/5) on Yelp', 'What a great evening; the food is excellent! We ordered 5 dishes and we enjoyed all of them. Everyone that goes here has to order the figs wrapped in bacon with blue cheese... One of the nicest dishes…', 'http://www.yelp.com/biz/traif-brooklyn?hrid=OPBkfRPTvt3jpnwrq1pNMg', 'Tue, 23 Sep 2014 02:08:53  PST'),
(46, 2, 'Recent Reviews Near New York, NY', 'London C.''s Review of Carmine''s - New York (2/5) on Yelp', 'We had heard great things about this restaurant, but were disappointed in the service. We had a party of six, and were only served five pieces of veal for our table. Instead of adding one more piece,…', 'http://www.yelp.com/biz/carmines-new-york?hrid=q08JPHPZ5pWAd0Bs9xWghw', 'Tue, 23 Sep 2014 02:08:53  PST'),
(47, 2, 'Recent Reviews Near New York, NY', 'London C.''s Review of Upstate - New York (5/5) on Yelp', 'Besides the oysters and the excellent local beers we we served a perfectly balanced main dish of fish and vegetables (monkfish and brussels sprouts). Friendly and knowledgeable service (oyster…', 'http://www.yelp.com/biz/upstate-new-york-2?hrid=NUWTBldi7YdRxojAa4BxoA', 'Tue, 23 Sep 2014 02:02:22  PST'),
(48, 2, 'Recent Reviews Near New York, NY', 'Dan B.''s Review of Ghostery, Inc. - New York (2/5) on Yelp', 'When 16-bit was new #yesijustsaidthat I piloted my Mario through decrepit houses full of little ghosts. Then there was this one room with a huge ghost, like maybe the size of 20 of the regular ones.…', 'http://www.yelp.com/biz/ghostery-inc-new-york?hrid=B3ZZumVTmknymb-vSRxhWg', 'Tue, 23 Sep 2014 02:01:44  PST'),
(49, 2, 'Recent Reviews Near New York, NY', 'Stephanie C.''s Review of Asanda Aveda Spa Lounge - New York (5/5) on Yelp', 'Very professional and warm environment.  This is my second visit and I left even more pleased than the first time.  This venue continues to impress  me.  Lawrence was my massage therapist and I would…', 'http://www.yelp.com/biz/asanda-aveda-spa-lounge-new-york?hrid=D4vPIDjA9WzEAIldRrdbpA', 'Tue, 23 Sep 2014 01:58:50  PST'),
(50, 2, 'Recent Reviews Near New York, NY', 'Hyaemee K.''s Review of Mama''s Empanadas - Jackson Heights (4/5) on Yelp', 'I love their empanadas! They have so many different empanadas to choose from. I haven''t tried them all yet but my favorite so far are the Hawaiian and spinach&cheese. Also, love the pink sauce…', 'http://www.yelp.com/biz/mamas-empanadas-jackson-heights?hrid=Zzoj57PIr-7Whu2NMP4mqQ', 'Tue, 23 Sep 2014 01:53:52  PST'),
(51, 2, 'Recent Reviews Near New York, NY', 'Lyn T.''s Review of People + Pets - New York (4/5) on Yelp', 'Loved the basic bath and  sanitary clipping they did for my dog, priced very well too. Service is great. It''s missing 1 star only because my dog didn''t smell especially great, like other groomers. And…', 'http://www.yelp.com/biz/people-pets-new-york?hrid=80NreMUQuJdT4WdcH7Svtw', 'Tue, 23 Sep 2014 01:48:27  PST'),
(52, 2, 'Recent Reviews Near New York, NY', 'Lyn T.''s Review of Dogs Cats & Co - New York (5/5) on Yelp', 'I''ve tried various dog groomers around UES and this would have to be my favorite place. My dog leaves shiny, happy and smelling oh-so-good. \nPrice is decent for a basic wash, but for this price most…', 'http://www.yelp.com/biz/dogs-cats-and-co-new-york?hrid=SvsL77boQoZywGaxd9A4CQ', 'Tue, 23 Sep 2014 01:44:11  PST'),
(53, 2, 'Recent Reviews Near New York, NY', 'Lyn T.''s Review of Calling All Pets - New York (5/5) on Yelp', 'Quick service and home delivery for the heavy dog food cans and dry food, that you can''t carry home. This place had amazingly competitive prices and a great range of dog food. This will be my dogs…', 'http://www.yelp.com/biz/calling-all-pets-new-york?hrid=PsiEveCI-emLDMLBiGVK3A', 'Tue, 23 Sep 2014 01:38:42  PST'),
(54, 3, 'Ziarul Gandul', 'Cazul Robert Turcescu produce o reacţie în lanţ: OFIŢERUL ACOPERIT ar putea fi „descoperit” în Parlament', 'Fostul ministru al Apărării, senatorul Corneliu Dobriţoiu, îl cheamă la audieri în Parlament pe ministrul Apărării Mircea Duşa, pentru a da explicaţii în cazul Robert Turcescu-ofiţer acoperit al Armatei.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/XL3gbmgdZdc/cazul-robert-turcescu-produce-o-reactie-in-lant-ofiterul-acoperit-ar-putea-fi-descoperit-in-parlament-13328170', 'Tue, 23 Sep 2014 08:32:00 GMT'),
(55, 3, 'Ziarul Gandul', 'SCANDALUL MANUALELOR DIGITALE. Cum s-a modificat rezultatul licitaţiei manualelor în numai trei zile. Ministerul Educaţiei a reevaluat ofertele şi a stabilit 6 câştigători', 'Reprezentanţii editorilor din România arată dovada că Ministerul Educaţiei a fraudat licitaţia manualelor pentru clasele I şi a II-a. Din raportul intern de conformitate, întocmit de patru dintre reprezentanţii Ministerului reiese că niciuna dintre editurile participante nu a întocmit specificaţiile tehnice cerute în caietul de sarcini cerute, inclusiv SIVECO şi CD Press. Cu toate acestea, rezultatele procedurii de licitaţie semnate de Cristian Mirescu de la Centrul Naţional de Evaluare şi Examinare arată că totuşi că SIVECO şi CD Press întocmesc toate criteriile şi sunt conforme. \n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/zJOzikvLZBw/scandalul-manualelor-digitale-cum-s-a-modificat-rezultatul-licitatiei-manualelor-in-numai-trei-zile-ministerul-educatiei-a-reevaluat-ofertele-si-a-stabilit-6-castigatori-13320829', 'Tue, 23 Sep 2014 08:37:00 GMT'),
(56, 3, 'Ziarul Gandul', 'Simona Halep, ELIMINATĂ la turneul Premier 5 de la Wuhan (China)', 'Jucătoarea de tenis Simona Halep, locul 2 WTA şi cap de serie numărul 2, a fost învinsă, marţi, cu scorul de 2-6, 6-2, 6-3, de sportiva spaniolă Garbine Muguruza, locul 22 WTA, în turul doi al turneului de categorie Premier 5 de la Wuhan (China), cu premii de 2,44 milioane de dolari.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/kgSO9NjkFN8/simona-halep-eliminata-la-turneul-premier-5-de-la-wuhan-china-13327047', 'Tue, 23 Sep 2014 05:10:47 GMT'),
(57, 3, 'Ziarul Gandul', 'Negriţoiu: Nu ştiu dacă o să trăim din pensiile private sau nu, dar este bine să ai banii acolo', 'Şeful Autorităţii de Supraveghere Financiară, Mişu Negriţoiu, apreciază că este benefic pentru români să deţină anumite sume acumulate la sistemul de pensii private, chiar dacă "vor trăi din ele sau nu", urmând un model cultural şi de educaţie financiară, de a economisi pentru bătrâneţe.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/rfM6eaRpMM0/negritoiu-nu-stiu-daca-o-sa-traim-din-pensiile-private-sau-nu-dar-este-bine-sa-ai-banii-acolo-13329287', 'Tue, 23 Sep 2014 09:58:00 GMT'),
(58, 3, 'Ziarul Gandul', 'Furau motorină direct din ambulanţă printr-o metodă ingenioasă. Zeci de angajaţi vor fi anchetaţi', 'Cel puţin 30 de angajaţi ai Serviciului de Ambulanţă Judeţean Vaslui sunt cercetaţi în cadrul unei anchete interne după ce, în urma unei reclamaţii, s-a descoperit existenţa unui cep în rezervorul de combustibil al unei autosanitare, prin care se fura motorină. \n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/HzLXJdUpHrY/furau-motorina-direct-din-ambulanta-printr-o-metoda-ingenioasa-zeci-de-angajati-vor-fi-anchetati-13328787', 'Tue, 23 Sep 2014 09:22:38 GMT'),
(59, 3, 'Ziarul Gandul', 'Meleşcanu: ieri şef SIE, azi prezidenţiabil. ”Sunt dispus să avem alegeri prezidenţiale în 2016, cadrul legal protejează ofiţerii de informaţii, e un non-subiect”', 'Fostul director al SIE, Teodor Meleşcanu, şi-a depus la BEC candidatura la prezidenţiale, afirmând că tema ofiţerilor acoperiţi este un non subiect\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/LpdxyQ8XvQI/melescanu-ieri-sef-sie-azi-prezidentiabil-sunt-dispus-sa-avem-alegeri-prezidentiale-in-2016-cadrul-legal-protejeaza-ofiterii-de-informatii-e-un-non-subiect-13328108', 'Tue, 23 Sep 2014 08:29:00 GMT'),
(60, 3, 'Ziarul Gandul', 'PACEA DIN UCRAINA. Separatiştii proruşi anunţă retragerea artileriei din zonele din care s-a retras şi armata', 'Rebelii proruşi au anunţat marţi că au început retragerea artileriei în estul Ucrainei, din zonele din care s-a retras şi armata ucraineană, conform acordului negociat la Minsk, relatează AFP.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/htQAfkS6F4U/pacea-din-ucraina-separatistii-prorusi-anunta-retragerea-artileriei-din-zonele-din-care-s-a-retras-si-armata-13328449', 'Tue, 23 Sep 2014 08:40:57 GMT'),
(61, 3, 'Ziarul Gandul', 'Bărbatul care a pătruns în Casa Albă avea un cuţit, însă adevăratul arsenal l-au găsit în maşina lui', 'Bărbatul care a pătruns vineri în Casa Albă deţinea munţii şi reprezenta "un pericol pentru preşedintele" Barack Obama , a declarat luni un procuror federal, citat de AFP.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/qV0b3-f7Cw0/barbatul-care-a-patruns-in-casa-alba-avea-un-cutit-insa-adevaratul-arsenal-l-au-gasit-in-masina-lui-13328626', 'Tue, 23 Sep 2014 09:02:12 GMT'),
(62, 3, 'Ziarul Gandul', 'Au încercat să vândă droguri de 50.000 de euro într-o parcare din Craiova. Unul dintre traficanţi este student la Teologie', 'Trei tineri au fost reţinuţi după ce au fost prinşi în flagrant de ofiţerii Serviciului de Combatere a Criminalităţii Organizate Mehedinţi în timp ce încercau să vândă un kilogram de heroină în parcarea unui complex comercial din Craiova, transmite corespondentul MEDIAFAX.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/rYZnu1ff81o/au-incercat-sa-vanda-droguri-de-50-000-de-euro-intr-o-parcare-din-craiova-unul-dintre-traficanti-este-student-la-teologie-13328548', 'Tue, 23 Sep 2014 08:48:28 GMT'),
(63, 3, 'Ziarul Gandul', 'Ponta vrea să propună el şeful SIE peste două luni, când va ajunge la Cotroceni, pentru că preşedintele în funcţie, Traian Băsescu, „nu mai are nicio legitimitate”', 'Preşedintele Traian Băsescu nu are niciun fel de legitimitate să mai propună ceva, astfel că noul şef al Serviciului de Informaţii Externe (SIE) trebuie propus Parlamentului de către viitorul preşedinte al ţării, a declarat liderul PSD, premierul Victor Ponta.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/76ePt1XEswA/ponta-vrea-sa-propuna-el-seful-sie-peste-doua-luni-cand-va-ajunge-la-cotroceni-pentru-ca-presedintele-in-functie-traian-basescu-nu-mai-are-nicio-legitimitate-13327386', 'Tue, 23 Sep 2014 06:35:00 GMT'),
(64, 3, 'Ziarul Gandul', 'Arafat: Una dintre victimele accidentului rutier din Bulgaria este paralizată ', 'Una dintre victimele accidentului rutier care a avut loc duminică în Bulgaria a suferit leziuni la coloana vertebrală şi este paralizată, a declarat marţi secretarul de stat în Ministerul Afacerilor Interne Raed Arafat.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/76UojarxaVk/arafat-una-dintre-victimele-accidentului-rutier-din-bulgaria-este-paralizata-13328578', 'Tue, 23 Sep 2014 08:51:58 GMT'),
(65, 3, 'Ziarul Gandul', 'Percheziţii la APIA Botoşani, într-un dosar de corupţie şi obţinere nelegală de fonduri europene\n', 'Procurorii DNA fac, marţi, 16 percheziţii în judeţele Botoşani şi Suceava, la sediul APIA Botoşani şi la cel al unei primării, precum şi la puncte de lucru ale unor firme, într-un dosar privind fapte de corupţie şi obţinere nelegală de fonduri europene.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/ZRRp1DuFUeQ/perchezitii-la-apia-botosani-intr-un-dosar-de-coruptie-si-obtinere-nelegala-de-fonduri-europene-13327307', 'Tue, 23 Sep 2014 06:22:00 GMT'),
(66, 3, 'Ziarul Gandul', 'Israelul anunţă ucidere celor doi palestinieni care au provocat ofensiva din Fâşia Gaza, soldată cu 2.200 de morţi', 'Cei doi palestinieni acuzaţi că au răpit şi asasinat trei tineri israelieni în iunie au fost ucişi, marţi, la Hebron, în Cisiordania, după o urmărire de trei luni, a anunţat purtătorul de cuvânt al armatei israeliene, relatează AFP. \n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/y4NWhCCS_TY/israelul-anunta-ucidere-celor-doi-palestinieni-care-au-provocat-ofensiva-din-fasia-gaza-soldata-cu-2-200-de-morti-13328599', 'Tue, 23 Sep 2014 08:57:49 GMT'),
(67, 3, 'Ziarul Gandul', 'Previziunea lui Iohannis: Eu voi obţine 35% în primul tur de scurtin, Ponta 36%, dar eu voi câştiga în turul II\n', ' Preşedintele PNL, Klaus Iohannis, estimează că în primul tur al prezidenţialelor va obţine 35% din voturile exprimate, premierul Victor Ponta urmând să aibă 36%, el opinând că pentru turul II de scrutin se va mobiliza toată lumea şi va câştiga alegerile, cu o prezenţă mai mare decât în primul tur.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/-FscvObXoy4/previziunea-lui-iohannis-eu-voi-obtine-35-in-primul-tur-de-scurtin-ponta-36-dar-eu-voi-castiga-in-turul-ii-13326866', 'Tue, 23 Sep 2014 04:19:00 GMT'),
(68, 3, 'Ziarul Gandul', 'O vizită a lui Vladimir Putin la Tokyo, SUSPENDATĂ la cererea SUA', 'Premierul japonez Shinzo Abe a renunţat să se mai întâlnească în acest an cu preşedintele rus Vladimir Putin din cauza tensiunilor legate de situaţia din Ucraina şi sancţiunilor japoneze împotriva Moscovei, a anunţat marţi presa locală, citată de AFP.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/dpHJlor8NB0/o-vizita-a-lui-vladimir-putin-la-tokyo-suspendata-la-cererea-sua-13327486', 'Tue, 23 Sep 2014 06:46:49 GMT'),
(69, 3, 'Ziarul Gandul', 'Armata americană a bombardat poziţii ale grupării Stat Islamic în Siria, anunţă Pentagonul ', 'Armata americană şi forţe ale unor ţări "partenere" au efectuat, pentru prima oară, raiduri aeriene contra unor poziţii ale grupării jihadiste Stat Islamic (SI) în Siria, a anunţat luni Pentagonul, relatează AFP.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/0lXJDwnE_aE/armata-americana-a-bombardat-pozitii-ale-gruparii-stat-islamic-in-siria-anunta-pentagonul-13326868', 'Tue, 23 Sep 2014 04:22:42 GMT'),
(70, 3, 'Ziarul Gandul', 'Parisul nu va negocia cu teroriştii Statului Islamic pentru a salva viaţa ostaticului francez', 'Franţa nu va avea "nicio discuţie, nicio negociere" cu răpitorii francezului luat ostatic duminică în Algeria, a afirmat marţi premierul Manuel Valls pentru postul privat de radio Europe 1, relatează AFP. \n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/fkkEyTR3PH8/parisul-nu-va-negocia-cu-teroristii-statului-islamic-pentru-a-salva-viata-ostaticului-francez-13328593', 'Tue, 23 Sep 2014 08:53:41 GMT'),
(71, 3, 'Ziarul Gandul', 'Coreea de Nord a dezvoltat rachete nucleare tactice', 'Coreea de Nord dezvoltă noi rachete care să poată fi echipate cu încărcătură nucleară pentru obţinerea unei arme nucleare tactice, au declarat serviciile de informaţii sud-coreene, reatează JoongAng Ilbo în ediţia electronică.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/kVh4DwjgbrM/coreea-de-nord-a-dezvoltat-rachete-nucleare-tactice-13327167', 'Tue, 23 Sep 2014 05:49:08 GMT'),
(72, 3, 'Ziarul Gandul', 'Bilanţ tragic al epidemiei Ebola: 5.864 de cazuri, 2.811 DE MORŢI', 'Epidemia de Ebola a provocat moartea a 2.811 de persoane în Africa de Vest din 5.864 de cazuri înregistrate, potrivit ultimului bilanţ al Organizaţiei Mondiale a Sănătăţii (OMS) actualizat luni seara, relatează AFP.\n												\n						\n						\n											', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/CNh6lZKhM9A/bilant-tragic-al-epidemiei-ebola-5-864-de-cazuri-2-811-de-morti-13326887', 'Tue, 23 Sep 2014 04:23:55 GMT'),
(73, 3, 'Ziarul Gandul', 'PRIMA REACŢIE a B1 TV după mărturisirea lui Robert Turcescu că a fost OFIŢER ACOPERIT. Banciu: „Tremura tot, a fost şantajat”', 'ULTIMA ORĂ\n										\n					\n					\n									', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/Eim6_NQLrhY/prima-reactie-a-b1-tv-dupa-marturisirea-lui-robert-turcescu-ca-a-fost-ofiter-acoperit-banciu-tremura-tot-a-fost-santajat-13327226', 'Tue, 23 Sep 2014 06:23:00 GMT'),
(74, 3, 'Ziarul Gandul', 'Halterofilii nord-coreeni reuşesc lucruri uimitoare la Jocurile Asiei, iar "drogul" lor ar fi Kim Jong-Un', 'Halterofilii din Coreea de Nord, care au stabilit mai multe recorduri mondiale la Jocurile Asiatice de la Incheon, au afirmat, marţi, că forţa lor vine din "iubirea" pentru liderul regimului comunist Kim Jong-Un, informează AFP.\n										\n					\n					\n									', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/DDZk9NPtRQ8/halterofilii-nord-coreeni-reusesc-lucruri-uimitoare-la-jocurile-asiei-iar-drogul-lor-ar-fi-kim-jong-un-13329229', 'Tue, 23 Sep 2014 09:57:05 GMT'),
(75, 3, 'Ziarul Gandul', 'Jumătate dintre americani cred ASTA despre religie şi politică', 'Jumătate dintre americani apreciază că bisericile ar trebui să se exprime în mod regulat asupra problemelor sociale şi politice, o cifră în sensibilă creştere în raport cu 2010, potrivit unui studiu al institutului Pew publicat luni, relatează AFP.\n										\n					\n					\n									', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/CM-khkEK5vc/jumatate-dintre-americani-cred-asta-despre-religie-si-politica-13326908', 'Tue, 23 Sep 2014 04:31:35 GMT'),
(76, 3, 'Ziarul Gandul', 'După eliminarea Simonei Halep, a venit rândul Serenei Williams să facă o surpriză', 'Numărul 1 mondial, Serena Williams, a abandonat, marţi, în turul doi al turneului de categorie Premier 5 de la Wuhan (China), cu premii de 2,44 milioane de dolari.\n										\n					\n					\n									', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/V30IbEJolgs/dupa-eliminarea-simonei-halep-a-venit-randul-serenei-williams-sa-faca-o-surpriza-13328912', 'Tue, 23 Sep 2014 09:33:00 GMT'),
(77, 3, 'Ziarul Gandul', 'Spectacolul care a obţinut încasări de 6,2 miliarde de dolari - TRAILER', 'Spectacolul de teatru "Regele Leu/ The Lion King" este producţia de divertisment cu cele mai mari încasări din lume, din orice domeniu, cu 6,2 miliarde de dolari obţinuţi la nivel mondial, potrivit unui purtător de cuvânt al Walt Disney Co., transmite Reuters.\n										\n					\n					\n									', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/JMYc1t9KWBU/spectacolul-care-a-obtinut-incasari-de-6-2-miliarde-de-dolari-trailer-13328486', 'Tue, 23 Sep 2014 08:44:00 GMT'),
(78, 3, 'Ziarul Gandul', 'Pink Floyd a anunţat data la care îşi lansează noul album', '"The Endless River", primul album de studio al trupei britanice Pink Floyd după o pauză de 20 de ani, va fi lansat pe 10 noiembrie, au anunţat, luni, membrii legendarului grup rock, care au prezentat, de asemenea, coperta noului disc într-o fotografie publicată pe site-ul formaţiei, informează AFP.\n										\n					\n					\n									', 'http://feedproxy.google.com/~r/gandul/MJcu/~3/L5iaoDgQXoE/pink-floyd-a-anuntat-data-la-care-isi-lanseaza-noul-album-13328572', 'Tue, 23 Sep 2014 08:49:00 GMT'),
(79, 3, 'REALITATEA.NET - Stiri - Ştiri', 'PREMIERĂ în România. Sistem de încălzire centralizat, bazat pe PROGNOZA METEO', 'Firma Krobath Romania, subsidiara locala a grupului austriac Ferdinand Krobath, a lansat luni un sistem de reglare a caldurii in apartamente, bazat pe prognoza meteo, care permite reduceri cu 10-15% la factura la incalzire. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebd132d/l/0L0Srealitatea0Bnet0Cpremiera0Ein0Eromania0Esistem0Ede0Eincalzire0Ecentralizat0Ebazat0Epe0Eprognoza0Emeteo0I15315250Bhtml/story01.htm', 'Tue, 23 Sep 2014 10:21:11 GMT'),
(80, 3, 'REALITATEA.NET - Stiri - Ştiri', 'NOWCASTING. COD GALBEN de PLOI în AVERSĂ în Bucureşti şi alte judeţe', 'COD GALBEN. Administraţia Naţională de Meteorologie a emis o avertizare tip nowcasting de cod galben de ploi şi v&amp;acirc;nt puternic. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebd114a/l/0L0Srealitatea0Bnet0Cnowcasting0Ecod0Egalben0Ede0Eploi0Ein0Eaversa0Ein0Ebucuresti0Esi0Ealte0Ejudete0I15315230Bhtml/story01.htm', 'Tue, 23 Sep 2014 10:14:51 GMT'),
(81, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Chilipir cât China: CELE MAI BUNE camere foto din România la preț mic', 'Odată cu toamna se deschide și sezonul de reduceri la gadgeturi. Playtech prezintă cele mai bune camere foto pe care le poți avea. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebd1153/l/0L0Srealitatea0Bnet0Ccamere0Efoto0Epe0Ecare0Ele0Ecumperi0Ecu0Emarun0Eis0Eiata0Ele0Epe0Ecele0Emai0Ebune0Edin0Eromania0I153150A90Bhtml/story01.htm', 'Tue, 23 Sep 2014 10:12:42 GMT'),
(82, 3, 'REALITATEA.NET - Stiri - Ştiri', 'BREAKING NEWS: Tiberiu Niţu: Parchetul s-ar putea autosesiza în cazul Turcescu. Evaluăm situaţia', 'Procurorul general, Tiberiu Niţu, a declarat marţi că parchetul s-ar putea autosesiza &amp;icirc;n cazul jurnalistului Robert Turcescu, care a anunţat că a fost ofiţer sub acoperire. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebcee7a/l/0L0Srealitatea0Bnet0Ctiberiu0Enitu0Eparchetul0Es0Ear0Eputea0Eautosesiza0Ein0Ecazul0Eturcescu0Eanalizam0Esituatia0I1531510A0Bhtml/story01.htm', 'Tue, 23 Sep 2014 10:10:33 GMT'),
(83, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Raluca Turcan, către Pricopie: Demisia nu este un gest de umilință, ci gest de responsabilitate', 'Deputatul PDL Raluca Turcan a declarat că Opoziția așteaptă demisia ministrului Educației, Remus Pricopie, susțin&amp;acirc;nd că nu este o umilință, ci poate fi un gest de responsabilitate. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebcee7d/l/0L0Srealitatea0Bnet0Craluca0Eturcan0Ecatre0Epricopie0Edemisia0Enu0Eeste0Eun0Egest0Ede0Eumilin0Ea0Eci0Egest0Ede0Eresponsabilitate0I153150A50Bhtml/story01.htm', 'Tue, 23 Sep 2014 10:06:54 GMT'),
(84, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Televizoare cum nici nu visai sunt acum la PREȚ REDUS. Iată cele mai bune modele', 'Fie că ești &amp;icirc;n căutarea unui televizor pe care să &amp;icirc;l folosești pe post de monitor, fie a unui televizor inteligent pe care să te poți juca oferta este mare și ai de unde alege. Iată cele mai bune televizoare pe care să le cumperi acum. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebceabf/l/0L0Srealitatea0Bnet0Ctelevizoare0Ecum0Enici0Enu0Evisai0Esunt0Eacum0Ela0Epre0Eredus0Eiata0Ecele0Emai0Ebune0Emodele0I153150A20Bhtml/story01.htm', 'Tue, 23 Sep 2014 10:00:30 GMT'),
(85, 3, 'REALITATEA.NET - Stiri - Ştiri', 'De ce candidează TEODOR MELEȘCANU. Află la Jocuri de Putere, ora 22.00', 'In aceasta seara de la ora 22.00 la &quot;Jocuri de putere&quot; invitatul meu si al Dumneavoastra este fostul sef al SIE pana ieri, TEODOR MELESCANU. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebceac8/l/0L0Srealitatea0Bnet0Cde0Ece0Ecandideaza0Eteodor0Emele0Ecanu0Eafla0Ela0Ejocuri0Ede0Eputere0Eora0E220E0A0A0I153150A0A0Bhtml/story01.htm', 'Tue, 23 Sep 2014 10:00:24 GMT'),
(86, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Acestea sunt semnele care ar putea anunța prezența unui cancer!', 'Este important să fie conștientă de orice modificare inexplicabilă a corpului, cum este apariția bruscă a unui nodul sau prezența s&amp;acirc;ngelui &amp;icirc;n urină. Sunt semne și simptome care pot anunța un posibil cancer. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebceacf/l/0L0Srealitatea0Bnet0Cacestea0Esunt0Esemnele0Ecare0Ear0Eputea0Eanun0Ea0Eprezen0Ea0Eunui0Ecancer0I15314980Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:58:32 GMT'),
(87, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Meleşcanu: Nu e nevoie de numirea unui nou director SIE înainte de alegeri', 'Fostul şef al SIE Teodor Meleşcanu a declarat, marţi, că, &amp;icirc;n opinia sa, nu este necesară numirea unui nou director al Serviciului &amp;icirc;nainte de alegerile prezidenţiale. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebcead4/l/0L0Srealitatea0Bnet0Cmelescanu0Enu0Ee0Enevoie0Ede0Enumirea0Eunui0Enou0Edirector0Esie0Einainte0Ede0Ealegeri0I1531490A0Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:55:37 GMT'),
(88, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Traian Băsescu a promulgat AMNISTIEREA propusă de PONTA', '&amp;nbsp;Președintele Traian Băsescu a semnat două decrete prin care a promulgat amnistierile propuse de Victor Ponta pentru mame și pensionari. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebca985/l/0L0Srealitatea0Bnet0Cbasescu0Ea0Epromulgat0Eamnistierea0Epropusa0Ede0Eponta0I15314910Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:53:13 GMT'),
(89, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Cele mai bune telefoane pe care să le cumperi: și ieftine, și foarte bune', 'Se apropie Black Friday și tot mai multe magazine pregătesc reduceri &amp;icirc;n perioada asta. &amp;bdquo;Playtech&amp;ldquo; a comparat unele dintre cele mai populare telefoane de acum și &amp;icirc;ți spune care merită cumpărate. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebca98d/l/0L0Srealitatea0Bnet0Ccele0Emai0Ebune0Etelefoane0Epe0Ecare0Esa0Ele0Ecumperi0Ei0Eieftine0Ei0Efoarte0Ebune0I15314890Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:51:35 GMT'),
(90, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Află cum scapi de urmele lăsate de acnee!', 'Leziunile acneice pot fi reduse cu ajutorul unor procedee moderne, indicate de medicul dermatolog. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce7e4/l/0L0Srealitatea0Bnet0Cafla0Ecum0Escapi0Ede0Eurmele0Elasate0Ede0Eacnee0I15314760Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:43:43 GMT'),
(91, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Noul album Pink Floyd, după o pauză de 20 de ani, va fi lansat pe 10 noiembrie', '&quot;The Endless River&quot;, primul album de studio al trupei britanice Pink Floyd după o pauză de 20 de ani, va fi lansat pe 10 noiembrie, au anunţat, luni, membrii legendarului grup rock, care au prezentat, de asemenea, coperta noului disc &amp;icirc;ntr-o fotografie ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce54c/l/0L0Srealitatea0Bnet0Cnoul0Ealbum0Epink0Efloyd0Edupa0Eo0Epauza0Ede0E20A0Ede0Eani0Eva0Efi0Elansat0Epe0E10A0Enoiembrie0I15314690Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:42:09 GMT'),
(92, 3, 'REALITATEA.NET - Stiri - Ştiri', 'CCR a mai primit încă patru contestații pentru candidaturile la prezidențiale. Cine este vizat', 'Curtea Constituțională a Rom&amp;acirc;niei (CCR) a primit, marți dimineață, &amp;icirc;ncă patru contestații referitoare la &amp;icirc;nregistrarea candidaturilor lui Victor Ponta, Klaus Iohannis, Monica Macovei și Călin Popescu-Tăriceanu pentru alegerile prezidențiale. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce552/l/0L0Srealitatea0Bnet0Cccr0Ea0Emai0Eprimit0Einca0Epatru0Econtesta0Eii0Epentru0Ecandidaturile0Ela0Epreziden0Eiale0I15314710Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:42:02 GMT'),
(93, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Dobriţoiu: Legea nu-i interzice lui Meleşcanu să candideze. Nu cred că are şanse', 'Fostul ministru al Apărării Corneliu Dobriţoiu a declarat marţi că legea nu &amp;icirc;i interzice lui Teodor Meleşcanu să candideze la Preşedinţie, menţion&amp;acirc;nd că &amp;icirc;i doreşte succes fostului liberal, dar că nu crede că acesta are şanse să intre ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce559/l/0L0Srealitatea0Bnet0Cdobritoiu0Elegea0Enu0Ei0Einterzice0Elui0Emelescanu0Esa0Ecandideze0Enu0Ecred0Eca0Eare0Esanse0I15314650Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:38:07 GMT'),
(94, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Cum arată soția lui James bond', 'Chiar dacă sunt de 13 ani &amp;icirc;mpreună, Pierce Brosnan şi soţia sa, Keeley, par mai fericiţi ca niciodată. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce560/l/0L0Srealitatea0Bnet0Ccum0Earata0Eso0Eia0Elui0Ejames0Ebond0I1531460A0Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:37:49 GMT'),
(95, 3, 'REALITATEA.NET - Stiri - Ştiri', 'SE SCHIMBĂ BANII: noi bancnote chiar de ASTĂZI', 'Noile bancnote de 10 euro intră &amp;icirc;n circulaţie &amp;icirc;ncep&amp;acirc;nd cu data de 23 septembrie 2014. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce567/l/0L0Srealitatea0Bnet0Cse0Eschimba0Ebanii0Enoi0Ebancnote0Echiar0Ede0Eastazi0I15314590Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:30:23 GMT'),
(96, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Ce spune Meleşcanu despre CANDIDATUL OFIŢER ACOPERIT', 'Fostul şef al SIE Teodor Meleşcanu a fost &amp;icirc;ntrebat, marţi, dacă subiectul candidatului la Preşedinţie ofiţer acoperit va marca această campanie electorală, el răspunz&amp;acirc;nd că, &amp;icirc;n opinia sa, acesta este un ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce56f/l/0L0Srealitatea0Bnet0Cce0Espune0Emelescanu0Edespre0Ecandidatul0Eofiter0Eacoperit0I15314580Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:28:27 GMT'),
(97, 3, 'REALITATEA.NET - Stiri - Ştiri', 'JOCURI DE RĂZBOI. 12.500 de militari din nouă state NATO, în Polonia', 'Un important exerciţiu militar &amp;icirc;ncepe miercuri &amp;icirc;n Polonia, la care participă 12.500 de militari, dintre care 750 sunt din alte opt state membre NATO, a anunţat Ministerul polonez al Apărării, citat de AFP, notează Mediafax. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce575/l/0L0Srealitatea0Bnet0Cjocuri0Ede0Erazboi0E120E50A0A0Ede0Emilitari0Edin0Enoua0Estate0Enato0Ein0Epolonia0I15314540Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:25:16 GMT'),
(98, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Adrian Năstase, PRIMA APARIŢIE într-o emisiune TV, la o LUNĂ de la ieşirea din închisoare', 'Adrian Năstase va participa, la o lună de la eliberarea sa din &amp;icirc;nchisoare, la prima emisiune de televiziune, la televiziunea publică, la emisiunea &quot;Vorbeşte liber&quot;. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce580/l/0L0Srealitatea0Bnet0Cadrian0Enastase0Eprima0Eaparitie0Eintr0Eo0Eemisiune0Etv0Ela0Eo0Eluna0Ede0Ela0Eiesirea0Edin0Einchisoare0I15314550Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:24:44 GMT'),
(99, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Pricopie, în plenul Camerei: Într-un timp foarte scurt manualele digitale vor fi în şcoli', 'Ministrul Educaţiei, Remus Pricopie, a declarat, marţi, &amp;icirc;n plenul Camerei Deputaţilor, la dezbaterea moţiunii simple pe educaţie iniţiată de ACL, că &amp;rdquo;&amp;icirc;ntr-un timp foarte scurt&amp;rdquo; manualele digitale vor fi &amp;icirc;n şcoli. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce586/l/0L0Srealitatea0Bnet0Cpricopie0Ein0Eplenul0Ecamerei0Eintr0Eun0Etimp0Efoarte0Escurt0Emanualele0Edigitale0Evor0Efi0Ein0Escoli0I15314530Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:22:27 GMT'),
(100, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Pe 23 și 24 septembrie facem maraton de cântări la Cupa Agențiilor la Karaoke', 'Palatul Bragadiru (Calea Rahovei, 147-153) va fi gazda&amp;nbsp;primei ediții&amp;nbsp;a Cupei Agențiilor la Karaoke by Cat Music, care are loc &amp;icirc;ntre 23 și 24 septembrie. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce58c/l/0L0Srealitatea0Bnet0Cpe0E230Ei0E240Eseptembrie0Efacem0Emaraton0Ede0Ecantari0Ela0Ecupa0Eagen0Eiilor0Ela0Ekaraoke0I15314480Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:18:10 GMT'),
(101, 3, 'REALITATEA.NET - Stiri - Ştiri', '"La noi, e IMPOSIBIL să stai peste program". La sfârşitul zilei, birourile DISPAR', 'Oricine ar vrea să lucreze la această firmă: aici, munca peste program este imposibilă, deoarece o simplă comandă din sistemul software face ca birourile să dispară automat la ora 18.00 ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce591/l/0L0Srealitatea0Bnet0Cla0Enoi0Emunca0Epeste0Eprogram0Ee0Eimposibila0Ela0Esfarsitul0Ezilei0Ebirourile0Edispar0I15314430Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:15:21 GMT'),
(102, 3, 'REALITATEA.NET - Stiri - Ştiri', 'ACCIDENT GRAV, provocat de un tânăr BEAT şi fără permis de conducere', 'Un t&amp;acirc;năr inconştient a provocat un accident grav pe DN 15, &amp;icirc;n localitatea S&amp;icirc;ngeorgiu de Mureş. Potrivit poliţiştilor, t&amp;acirc;nărul vinovat de producerea acestui accident grav nu avea permis de conducere şi era beat la volan. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce597/l/0L0Srealitatea0Bnet0Caccident0Egrav0Eprovocat0Ede0Eun0Etanar0Ebeat0Esi0Efara0Epermis0Ede0Econducere0I15314310Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:05:36 GMT'),
(103, 3, 'REALITATEA.NET - Stiri - Ştiri', 'Un deputat a plecat de la PDL la grupul PC- PNL. Cine este acesta', 'Deputatul Romeo Rădulescu demisionează din grupul parlamentar al PDL și se afiliază grupului liberal-conservator, a anunțat marți președintele Camerei Deputaților, Valeriu Zgonea. ', 'http://realitatea.feedsportal.com/c/32533/f/501838/s/3ebce59c/l/0L0Srealitatea0Bnet0Cun0Edeputat0Ea0Eplecat0Ede0Ela0Epdl0Ela0Egrupul0Epc0Epnl0Ecine0Eeste0Eacesta0I15314340Bhtml/story01.htm', 'Tue, 23 Sep 2014 09:00:10 GMT');

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `rss`
--

CREATE TABLE IF NOT EXISTS `rss` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_id` int(11) NOT NULL,
  `link` varchar(255) NOT NULL,
  `active` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Salvarea datelor din tabel `rss`
--

INSERT INTO `rss` (`id`, `country_id`, `link`, `active`) VALUES
(1, 2, 'http://rss.cnn.com/rss/edition.rss', 1),
(2, 2, 'http://www.yelp.com/syndicate/area/rss.xml?loc=New+York%2C+NY', 1),
(3, 3, 'http://feeds.feedburner.com/gandul/Mjcu', 1),
(4, 3, 'http://realitatea.feedsportal.com/c/32533/fe.ed/rss.realitatea.net/stiri.xml', 1);

-- --------------------------------------------------------

--
-- Structura de tabel pentru tabelul `slugs`
--

CREATE TABLE IF NOT EXISTS `slugs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `country2` varchar(255) NOT NULL,
  `timezone` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Salvarea datelor din tabel `slugs`
--

INSERT INTO `slugs` (`id`, `country`, `slug`, `country2`, `timezone`) VALUES
(1, 'Netherlands', 'nl', 'Nederland', 4),
(2, 'United States', 'us', 'United States', 13),
(3, 'Romania', 'ro', 'România', 13);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
